<h4>11-12月調課資訊：</h4>

<p>由於印尼招生(自112/11/19(日)至112/11/23(四))以及參加國際會議(自112/12/08(五)至112/12/12(二))，將數值最佳化的上課時間(11/22(三)10:10AM-12:00PM、12/8(五)9:10AM-10:00AM)進行調動，調動如下：

<ol>
    <li>11/22(三)10:10AM-11:00AM 調整至 11/3(五)  8:10AM:-9:00AM</li>
    <li>11/22(三)11:10AM-12:00PM 調整至 11/17(五)8:10AM:-9:00AM</li>
    <li>12/8(五)  9:10AM-10:00AM   調整至 11/24(五)8:10AM:-9:00AM</li>
</ol>
</p>
    
造成不便，請多多見諒

JYL

In [1]:
import numpy as np
import random
import pandas as pd


<h3>Theorem:</h3>

Suppose that $f({\bf x})$ is twice differentiable at $\bar{\bf x}$. If $\nabla f(\bar{\bf x}) = 0$ and the hession matrix $H(\bar{\bf x})$ is positive definite, then $\bar{\bf x}$ is a (strict) local minimum.
<hr>

<h3>Theorem:</h3>

Suppose $f({\bf x}) : X \rightarrow \mathbb{R}$ is convex and differentiable on $X$.
Then $\bar{\bf{x}} \in X$ is a global minimum if and only if $\nabla f(\bar{\bf{x}}) = 0$.

In [2]:
#https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html
Q=np.array([[10,4],[4,2]])
q=np.array([[-14],[-6]])
f0=np.array([[20]])
-np.linalg.inv(Q).dot(q)

array([[1.],
       [1.]])

In [3]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
-np.linalg.inv(Q).dot(q)

array([[-0.13333333],
       [ 3.33333333]])

In [4]:
Q=np.array([[20,5],[5,16]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
-np.linalg.inv(Q).dot(q)

array([[0.65762712],
       [0.16949153]])

In [5]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
dk=[]
alphak=[]
#dk.append
dk.append(-functionGradient(xk[k],Q,q))
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    #print("%d Step:" % k)
    #alphak.append
    alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    #print(dk[k])
    xk.append(xk[k]+alphak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#empty list
for i in range(10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
for i in range(19,len(alphak),10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
finalSeg=i+1
for i in range(finalSeg,len(alphak)):    
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"norm":norm_d0,"Step Size":alphak0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

The optimal value is reported as 0.933333
An optimal solution is given by (-0.133333,3.333332)


k  $x_{1}^{k}$  $x_{2}^{k}$        norm  Step Size          函數值
0    1    40.000000  -100.000000  286.062930   0.050550  6050.000000
1    2    25.542693   -99.696700   77.697029   0.450935  3981.695128
2    3    26.277558   -64.668130  188.251915   0.050550  2620.587793
3    4    16.763512   -64.468535   51.130758   0.450935  1724.872077
4    5    17.247111   -41.416980  123.884571   0.050550  1135.420663
5    6    10.986120   -41.285630   33.648062   0.450935   747.515255
6    7    11.304366   -26.115894   81.525795   0.050550   492.242977
7    8     7.184142   -26.029455   22.143072   0.450935   324.253734
8    9     7.393573   -16.046575   53.650387   0.050550   213.703595
9   10     4.682141   -15.989692   14.571884   0.450935   140.952906
10  20     0.460997     0.948466    1.798477   0.450935     3.066216
11  30    -0.059980     3.038991    0.221970   0.450935     0.965823
12  40    -0.124280     3.297005    0.027396   0.450935     0.933828
13  50    -0.132216     3.328850    0.003381   0.450935     0.933341
14  60    -0.133195     3.332780    0.000417   0.450935     0.933333
15  70    -0.133316     3.333265    0.000052   0.450935     0.933333
16  80    -0.133331     3.333325    0.000006   0.450935     0.933333
17  81    -0.133331     3.333328    0.000015   0.050550     0.933333
18  82    -0.133332     3.333328    0.000004   0.450935     0.933333
19  83    -0.133332     3.333330    0.000010   0.050550     0.933333
20  84    -0.133332     3.333330    0.000003   0.450935     0.933333
21  85    -0.133332     3.333331    0.000007   0.050550     0.933333
22  86    -0.133333     3.333331    0.000002   0.450935     0.933333
23  87    -0.133333     3.333332    0.000004   0.050550     0.933333
24  88    -0.133333     3.333332    0.000001   0.450935     0.933333
25  89    -0.133333     3.333332    0.000003   0.050550     0.933333

<h3>Inner Product Spaces</h3>
Throughout this file we assume that
<ul>
    <li>The matrix $Q$ is a positive definite symmetric matrix.</li>
    <li>The inner product notation
$$
<{\bf x},{\bf y}>_{Q}={\bf x}^tQ {\bf y}.
$$
where ${\bf x}$ and ${\bf y}$ are $n$-dimensional vectors.</li>
    <li>Some additional standard results from linear algebra.</li>
</ul>
<hr>

<h3>Convergence Theorem of CG Method:</h3>

Let $$\{{\rm {\bf d}}^{1}, {\rm {\bf d}}^{2}, \cdots,{\rm {\bf d}}^{n}\}$$ be an $Q$-orthogonal set of nonzero vectors associated with the positive
definite matrix $Q$, and let ${\bf x}^{1}$ be arbitrary. Define
$$
t^k=\frac{<{\rm {\bf d}}^{k},-(Q{\bf x}^{k}+{\bf q})>}{<{\rm {\bf d}}^{k},Q{\rm {\bf d}}^{k}>} \hbox{ and } {\bf x}^{k+1}={\bf x}^{k}+t^k{\rm {\bf d}}^{k},
$$
for $k = 1, 2,\cdots,n$. Then, assuming exact arithmetic, $Q{\bf x}^{(n+1)} + {\bf q}=0$. |

<h3>Example of CG Method</h3>
Suppose that we seek to minimize
    $$f({\bf x}) = \displaystyle \frac{1}{2}{\bf x}^{t}Q{\bf x} +{\bf q}^{t}{\bf x} ,$$
    where
    \[
    Q = \left[
    \begin{array}{ccc}
        4 & 3 & 0 \\
        3 & 4 & -1 \\
        0 & -1 & 4
    \end{array}
    \right] \hbox{ and }
    {\bf q} = \left[
    \begin{array}{c}
        -24 \\
        -30 \\
        24
    \end{array}
    \right].
    \]
    Implement the CG on this problem, using the following starting points: ${\bf x}^{1} = (0,0,0)^{t}$.
    As it turns out, the optimal solution to this problem is ${\bf x}^{*} = (3,4,-5)^{t}$.
    
Given
    $$
        {\bf x}^{1}=\left[\begin{array}{c}0\\0\\0\end{array}\right]
    $$
    \item Given
    $$
        {\bf d}^{1}=\left[\begin{array}{c}1\\0\\0\end{array}\right],{\bf d}^{2}=\left[\begin{array}{c}\frac{-3}{4}\\1\\0\end{array}\right],{\bf d}^{3}=\left[\begin{array}{c}\frac{-3}{7}\\\frac{4}{7}\\1\end{array}\right]
    $$
    \item Then computing the following
    $$
        {\bf r}^{1}=-(Q{\bf x}^{1}+{\bf q}),t^{1}=\frac{({\bf d}^{1})^t{\bf r}^{1}}{({\bf d}^{1})^tQ{\bf d}^{1}}, {\bf x}^{2}={\bf x}^{1}+t^1{\bf d}^{1},
    $$
    $$
         {\bf r}^{2}=-(Q{\bf x}^{2}+{\bf q}),t^{2}=\frac{({\bf d}^{2})^t{\bf r}^{2}}{({\bf d}^{2})^tQ{\bf d}^{2}}, {\bf x}^{3}={\bf x}^{2}+t^2{\bf d}^{2},
    $$
    $$
         {\bf r}^{3}=-(Q{\bf x}^{3}+{\bf q}),t^{3}=\frac{({\bf d}^{3})^t{\bf r}^{3}}{({\bf d}^{3})^tQ{\bf d}^{3}}, {\bf x}^{4}={\bf x}^{3}+t^3{\bf d}^{3},
    $$ 

Define $f(x)=\frac{1}{2}{\bf x}^t Q {\bf x}^t +{\bf q}^t x$. Then the minimum of $f$ occurs on $\left\{x|Q{\bf x}+{\bf q}={\bf 0}\right\}$. Since $Q$ is positive-definite, $-Q^{-1}{\bf q}$ is the minimum point.

In [6]:
##############################################
Q=np.array([[4,3,0],[3,4,-1],[0,-1,4]])
q=np.array([[-24],[-30],[24]])
f0=np.array([[0]])
x1=np.array([[0],[0],[0]])
##############################################
d1=np.array([[1],[0],[0]])
d2=np.array([[-3/4],[1],[0]])
d3=np.array([[-3/7],[4/7],[1]])
##############################################
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d
print(x1)
##############################################
r1=-functionGradient(x1,Q,q)
t1=d1.transpose().dot(r1)/(d1.transpose().dot(Q).dot(d1))
x2=x1+t1*d1
print(x2)
##############################################
r2=-functionGradient(x2,Q,q)
t2=d2.transpose().dot(r2)/(d2.transpose().dot(Q).dot(d2))
x3=x2+t2*d2
print(x3)
##############################################
r3=-functionGradient(x3,Q,q)
t3=d3.transpose().dot(r3)/(d3.transpose().dot(Q).dot(d3))
x4=x3+t3*d3
print(x4)

[[0]
 [0]
 [0]]
[[6.]
 [0.]
 [0.]]
[[0.85714286]
 [6.85714286]
 [0.        ]]
[[ 3.]
 [ 4.]
 [-5.]]


https://en.wikipedia.org/wiki/Conjugate_gradient_method

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/021e02360a28c46188bc915eb06533dfa84a3002" with="600" heigh="400" alt="一張圖片">

<h1>Conjugate Gradient Method</h1>
<h4>Input</h4> <p>Input the number of equations and unknowns $n$; the matrix $Q$; the vector ${\bf q}$; the initial approximation ${\bf x}^{1}$</p>
<h4>Step 0:</h4> <p>Compute ${\bf r}^{1}=-(Q{\bf x}^{1}+{\bf q})$. Set $k=1$ and ${\bf d}^1={\bf r}^1$.</p>
<h4>Step 1:</h4> <p>If ${\bf r}^{k}=0$, Stop. Otherwise, compute
$$
\alpha^k=\frac{<{\bf r}^{k},{\bf r}^{k}>}{<{\bf d}^{k},{\bf d}^{k}>_{Q}}
\hbox{ and }
{\bf x}^{k+1}={\bf x}^{k}+\alpha^k{\bf d}^{k}
$$</p>
<h4>Step 2:</h4> <p>Compute ${\bf r}^{k+1}={\bf r}^{k}-\alpha^kQd^{k}$ and $\beta^{k}=\displaystyle \frac{<{\bf r}^{k+1},{\bf r}^{k+1}>}{<{\bf r}^{k},{\bf r}^{k}>}$.
<h4>Step 3:</h4> <p>Compute ${\bf d}^{k+1}={\bf r}^{k+1}+\beta^k{\bf d}^{k}$. Set $k=k+1$ and goto <span style="font-weight:bold;font-size:1em;">Step 1</span>.</p>
<hr>

<h1>Steepest Descent Method</h1>
    
<h4>Step 0:</h4> <p>Given ${\bf x}^{0}$, set $k:=0$</p>

<h4>Step 1:</h4> <p>${\bf d}^{k}:= -\nabla f({\bf x}^{k})=-(Q{\bf x}+{\bf q})$. If ${\bf d}^{k}=0$, then stop.</p>

<h4>Step 2:</h4> <p>Solve $\displaystyle \min_{\alpha >0} f({\bf x}^{k} + \alpha {\bf d}^{k})$ for the step size $\alpha^{k}$, perhaps chosen by an exact or inexact line search.</p>

<h4>Step 3:</h4> <p>Set ${\bf x}^{k+1} \leftarrow {\bf x}^{k} + \alpha^{k} {\bf d}^{k}$, $k \leftarrow k+1$.Go to goto <span style="font-weight:bold;font-size:1em;">Step 1</span>.</p>

<hr>

In [7]:
#保留
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
rk=[]
dk=[]
alphak=[]
#dk.append
rk.append(-functionGradient(xk[k],Q,q))
dk.append(rk[k])
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    print("%d Step:" % k)
    #alpha.append
    alphak.append(rk[k].transpose().dot(rk[k])/(dk[k].transpose().dot(Q).dot(dk[k])))
    #alphak.append
    #print(dk[k])
    xk.append(xk[k]+alphak[k]*dk[k])
    rk.append(rk[k]-alphak[k]*Q.dot(dk[k]))
    betak.qppend(rk[k+1].transpose().dot(rk[k+1])/(rk[k].transpose().dot(rk[k])))
    dk.append(rk[k+1]+betak[k]*dk[k])
    k=k+1
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#empty list
for i in range(len(alphak)):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    #alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])

Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"norm":norm_d0,"Step Size":alphak0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

0 Step:


NameError: name 'betak' is not defined

In [8]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
rk=[]
dk=[]
alphak=[]
betak=[]
#dk.append
rk.append(-functionGradient(xk[k],Q,q))
dk.append(rk[k])
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    print("%d Step:" % k)
    #alphak.append
    #alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    alphak.append(rk[k].transpose().dot(rk[k])/(dk[k].transpose().dot(Q).dot(dk[k])))
    xk.append(xk[k]+alphak[k]*dk[k])
    rk.append(rk[k]-alphak[k]*Q.dot(dk[k]))
    betak.append(rk[k+1].transpose().dot(rk[k+1])/(rk[k].transpose().dot(rk[k])))
    dk.append(rk[k+1]+betak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#empty list
for i in range(len(xk)):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    #alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"norm":norm_d0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

0 Step:
1 Step:
2 Step:
The optimal value is reported as 0.933333
An optimal solution is given by (-0.133333,3.333333)


k  $x_{1}^{k}$  $x_{2}^{k}$          norm          函數值
0  1    40.000000  -100.000000  2.860629e+02  6050.000000
1  2    25.542693   -99.696700  8.051193e+01  3981.695128
2  3    -0.133333     3.333333  7.769703e+01     0.933333
3  4    -0.133333     3.333333  9.970447e-13     0.933333

In [9]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
rk=[]
dk=[]
alphak=[]
betak=[]
#dk.append
rk.append(-functionGradient(xk[k],Q,q))
dk.append(rk[k])
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    #print("%d Step:" % k)
    #alphak.append
    #alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    
    print(determineStepSize(xk[k],Q,q,dk[k]))
    print(rk[k].transpose().dot(rk[k]/(dk[k].transpose().dot(Q).dot(dk[k]))))
    
    
    alphak.append(rk[k].transpose().dot(rk[k])/(dk[k].transpose().dot(Q).dot(dk[k])))
    xk.append(xk[k]+alphak[k]*dk[k])
    rk.append(rk[k]-alphak[k]*Q.dot(dk[k]))
    betak.append(rk[k+1].transpose().dot(rk[k+1])/(rk[k].transpose().dot(rk[k])))
    dk.append(rk[k+1]+betak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#empty list
for i in range(len(xk)):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    #alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"norm":norm_d0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

[0.05055003]
[[0.05055003]]
[1.31882556]
[[1.31882556]]
[1.60500615e-15]
[[7.42564076e-29]]
The optimal value is reported as 0.933333
An optimal solution is given by (-0.133333,3.333333)


k  $x_{1}^{k}$  $x_{2}^{k}$          norm          函數值
0  1    40.000000  -100.000000  2.860629e+02  6050.000000
1  2    25.542693   -99.696700  8.051193e+01  3981.695128
2  3    -0.133333     3.333333  7.769703e+01     0.933333
3  4    -0.133333     3.333333  9.970447e-13     0.933333

In [10]:
print(dk[0])
print(dk[1])
print(dk[0].transpose().dot(Q).dot(dk[1]))

[[-286]
 [   6]]
[[-19.46885668]
 [ 78.12256313]]
[[2.20552465e-10]]


In [11]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
rk=[]
dk=[]
alphak=[]
betak=[]
#dk.append
rk.append(-functionGradient(xk[k],Q,q))
dk.append(rk[k])
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    #print("%d Step:" % k)
    #alphak.append
    #alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    
    print(determineStepSize(xk[k],Q,q,dk[k]))
    print(rk[k].transpose().dot(rk[k]/(dk[k].transpose().dot(Q).dot(dk[k]))))
    
    
    alphak.append(rk[k].transpose().dot(rk[k])/(dk[k].transpose().dot(Q).dot(dk[k])))
    xk.append(xk[k]+alphak[k]*dk[k])
    rk.append(rk[k]-alphak[k]*Q.dot(dk[k]))
    
    print(rk[k]-alphak[k]*Q.dot(dk[k]))
    print(-functionGradient(xk[k+1],Q,q))
    
    betak.append(rk[k+1].transpose().dot(rk[k+1])/(rk[k].transpose().dot(rk[k])))
    dk.append(rk[k+1]+betak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#empty list
for i in range(len(xk)):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    #alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"norm":norm_d0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

[0.05055003]
[[0.05055003]]
[[ 1.62964903]
 [77.67993714]]
[[ 1.62964903]
 [77.67993714]]
[1.31882556]
[[1.31882556]]
[[9.63673585e-13]
 [2.55795385e-13]]
[[1.00897068e-12]
 [2.55795385e-13]]
[1.60500615e-15]
[[7.42564076e-29]]
[[9.63673585e-13]
 [2.55795385e-13]]
[[1.00897068e-12]
 [2.55795385e-13]]
The optimal value is reported as 0.933333
An optimal solution is given by (-0.133333,3.333333)


k  $x_{1}^{k}$  $x_{2}^{k}$          norm          函數值
0  1    40.000000  -100.000000  2.860629e+02  6050.000000
1  2    25.542693   -99.696700  8.051193e+01  3981.695128
2  3    -0.133333     3.333333  7.769703e+01     0.933333
3  4    -0.133333     3.333333  9.970447e-13     0.933333

In [12]:
Q=np.array([[1,0],[0,-1]])
q=np.array([[0],[0]])
f0=np.array([[0]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
dk=[]
alphak=[]
#dk.append
dk.append(-functionGradient(xk[k],Q,q))
while np.linalg.norm(dk[k])>1e-6 and k<=10000:
    print("%d Step:" % k)
    #alphak.append
    alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    #print(dk[k])
    xk.append(xk[k]+alphak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
    print(xk[k])
    print(functionValue(xk[k],Q,q,f0))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))


0 Step:
[[95.23809524]
 [38.0952381 ]]
[[3809.52380952]]
1 Step:
[[-36.28117914]
 [ 90.70294785]]
[[-3455.35039413]]
2 Step:
[[-86.38375985]
 [-34.55350394]]
[[3134.10466587]]
3 Step:
[[ 32.90809899]
 [-82.27024748]]
[[-2842.72532052]]
4 Step:
[[78.35261665]
 [31.34104666]]
[[2578.43566487]]
5 Step:
[[-29.84861587]
 [ 74.62153966]]
[[-2338.71715635]]
6 Step:
[[-71.06813301]
 [-28.42725321]]
[[2121.28540258]]
7 Step:
[[ 27.07357448]
 [-67.6839362 ]]
[[-1924.06839236]]
8 Step:
[[64.46089162]
 [25.78435665]]
[[1745.18675044]]
9 Step:
[[-24.55653014]
 [ 61.39132535]]
[[-1582.93582807]]
10 Step:
[[-58.46792891]
 [-23.38717156]]
[[1435.76945856]]
11 Step:
[[ 22.27349673]
 [-55.68374182]]
[[-1302.28522319]]
12 Step:
[[53.03213506]
 [21.21285403]]
[[1181.21108679]]
13 Step:
[[-20.20271812]
 [ 50.5067953 ]]
[[-1071.393276]]
14 Step:
[[-48.10170981]
 [-19.24068392]]
[[971.78528435]]
15 Step:
[[ 18.32446088]
 [-45.8111522 ]]
[[-881.43789964]]
16 Step:
[[43.62966876]
 [17.4518675 ]]
[[799.4901584]

In [13]:
Q=np.array([[1,0],[0,-1]])
q=np.array([[0],[0]])
f0=np.array([[0]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
rk=[]
dk=[]
alphak=[]
betak=[]
#dk.append
rk.append(-functionGradient(xk[k],Q,q))
dk.append(rk[k])
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    #print("%d Step:" % k)
    #alphak.append
    #alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    
    print(determineStepSize(xk[k],Q,q,dk[k]))
    print(rk[k].transpose().dot(rk[k]/(dk[k].transpose().dot(Q).dot(dk[k]))))
    
    
    alphak.append(rk[k].transpose().dot(rk[k])/(dk[k].transpose().dot(Q).dot(dk[k])))
    xk.append(xk[k]+alphak[k]*dk[k])
    rk.append(rk[k]-alphak[k]*Q.dot(dk[k]))
    betak.append(rk[k+1].transpose().dot(rk[k+1])/(rk[k].transpose().dot(rk[k])))
    dk.append(rk[k+1]+betak[k]*dk[k])
    k=k+1
    print(xk[k])
    print(functionValue(xk[k],Q,q,f0))
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))


[-1.38095238]
[[-1.38095238]]
[[95.23809524]
 [38.0952381 ]]
[[3809.52380952]]
[0.72413793]
[[0.72413793]]
[[-1.42108547e-14]
 [ 0.00000000e+00]]
[[1.00974196e-28]]
[-1.77635684e-16]
[[2.65057264e-32]]
[[-1.42108547e-14]
 [ 1.00974196e-30]]
[[1.00974196e-28]]
The optimal value is reported as 0.000000
An optimal solution is given by (-0.000000,0.000000)
