In [1]:
import numpy as np
import random
import pandas as pd

# Theoretic Analysis

Unconstrained Problem:
\begin{align*}
    (\text{P}) \quad \min \quad & f({\bf x})  \\
    \text{s.t. } \quad  & \bar{\bf x} \in X,
\end{align*}
where $\bar{\bf x}=(x_{1},\cdots,x_{n}) \in \mathbb{R}^{n}, f(\bar{\bf x}):\mathbb{R}^{n} \rightarrow \mathbb{R},$ and $X$ is an open set (usually $X = \mathbb{R}^{n}$).
<hr>
Definition:

The direction ${\bf d}$ is called a descent direction of $f({\bf x})$ at ${\bf x} = \bar{\bf x}$ if there is a $\varepsilon>0$ such that for all $\lambda\in(0,\varepsilon)$
$$
f(\bar{\bf x}+\lambda {\bf d}) < f(\bar{\bf x}).
$$
<hr>

A $necessary \, condition$ for local optimality is a statement of the form: "if $\bar{\bf x}$ is a local minimum of (P), then $\bar{\bf x}$ must satisfy$\ldots$". Such a condition helps us identify all candidates for local optima.
<hr>
Theorem:

Suppose that $f({\bf x})$ is differentiable at $\bar{\bf x}$. If there is a vector $d$ such that $\nabla f(\bar{\bf x})^{t}d < 0$,
then there is a $\varepsilon>0$ such that for all $\lambda\in(0,\varepsilon)$, $f(\bar{\bf x}+ \lambda {\bf d}) < f(\bar{\bf x})$, and hence $d$ is a descent direction of $f({\bf x})$ at $\bar{\bf x}$.
<hr>


<h3>Theorem:</h3>

Suppose that $f({\bf x})$ is twice differentiable at $\bar{\bf x}$. If $\nabla f(\bar{\bf x}) = 0$ and $H(\bar{\bf x})$ is positive definite, then $\bar{\bf x}$ is a (strict) local minimum.
<hr>

<h3>Definition:</h3>
<ul>
    <!--li>Let ${\bf x}, {\bf y} \in \mathbb{R}^{n}$. Points of the form $\lambda
    {\bf x}+(1 -\lambda){\bf y}$ for $\lambda \in \left[0, 1\right]$ are called
    convex combinations of ${\bf x}$ and ${\bf y}$.
    </li-->
    <!--li> A set $S  \subset \mathbb{R}^{n}$ is called a convex set if for all ${\bf x}, {\bf y} \in S$ and for all $\lambda \in \left[ 0, 1 \right]$ it holds that $\lambda {\bf x} + (1 - \lambda){\bf y} \in S$.
        </li-->
    <li> A function $f({\bf x}):S \rightarrow \mathbb{R}$, where $S$ is a nonempty convex set, is a convex function if
    $$f(\lambda {\bf x} +(1 - \lambda){\bf y}) \leq \lambda f({\bf x}) + (1 - \lambda)f({\bf y})$$
    for all ${\bf x},{\bf y} \in S$ and for all $\lambda \in \left[ 0, 1 \right]$.
        </li>
    <!--li> A function $f({\bf x})$ as above is called a strictly convex function if the
    inequality above is strict for all ${\bf x} \neq {\bf y}$ and $\lambda \in \left( 0, 1 \right)$.
        </li-->
    <!--li>
    A function $f({\bf x}):S \rightarrow \mathbb{R}$, where $S$ is a nonempty convex set, is a strictly convex function if
    $$f(\lambda {\bf x} +(1 - \lambda){\bf y}) < \lambda f({\bf x}) + (1 - \lambda)f({\bf y})$$
    for all ${\bf x}\neq {\bf y} \in S$ and for all $\lambda \in \left( 0, 1 \right)$.
        </li-->
</ul> 

<h3>Theorem:</h3>

Suppose $f({\bf x}) : X \rightarrow \mathbb{R}$ is convex and differentiable on $X$.
Then $\bar{\bf{x}} \in X$ is a global minimum if and only if $\nabla f(\bar{\bf{x}}) = 0$.

<p><b>This is why we use ``np.linalg.norm(dk[k])>1e-6'' as a stopping criteria.</b></p>
<hr>

In [2]:
Q=np.array([[10,4],[4,2]])
q=np.array([[-14],[-6]])
b=np.array([[20]])
-np.linalg.inv(Q).dot(q)

array([[1.],
       [1.]])

In [3]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
b=np.array([[10]])
-np.linalg.inv(Q).dot(q)

array([[-0.13333333],
       [ 3.33333333]])

In [4]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
xk=[np.array([[40],[-100]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
dk=[]
alphak=[]
#dk.append
dk.append(-functionGradient(xk[k],Q,q))
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    #print("%d Step:" % k)
    #alphak.append
    alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    #print(dk[k])
    xk.append(xk[k]+alphak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#empty list
for i in range(10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
for i in range(19,len(alphak),10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
finalSeg=i+1
for i in range(finalSeg,len(alphak)):    
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"norm":norm_d0,"Step Size":alphak0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

The optimal value is reported as 0.933333
An optimal solution is given by (-0.133333,3.333332)


k  $x_{1}^{k}$  $x_{2}^{k}$        norm  Step Size          函數值
0    1    40.000000  -100.000000  286.062930   0.050550  6050.000000
1    2    25.542693   -99.696700   77.697029   0.450935  3981.695128
2    3    26.277558   -64.668130  188.251915   0.050550  2620.587793
3    4    16.763512   -64.468535   51.130758   0.450935  1724.872077
4    5    17.247111   -41.416980  123.884571   0.050550  1135.420663
5    6    10.986120   -41.285630   33.648062   0.450935   747.515255
6    7    11.304366   -26.115894   81.525795   0.050550   492.242977
7    8     7.184142   -26.029455   22.143072   0.450935   324.253734
8    9     7.393573   -16.046575   53.650387   0.050550   213.703595
9   10     4.682141   -15.989692   14.571884   0.450935   140.952906
10  20     0.460997     0.948466    1.798477   0.450935     3.066216
11  30    -0.059980     3.038991    0.221970   0.450935     0.965823
12  40    -0.124280     3.297005    0.027396   0.450935     0.933828
13  50    -0.132216     3.328850    0.003381   0.450935     0.933341
14  60    -0.133195     3.332780    0.000417   0.450935     0.933333
15  70    -0.133316     3.333265    0.000052   0.450935     0.933333
16  80    -0.133331     3.333325    0.000006   0.450935     0.933333
17  81    -0.133331     3.333328    0.000015   0.050550     0.933333
18  82    -0.133332     3.333328    0.000004   0.450935     0.933333
19  83    -0.133332     3.333330    0.000010   0.050550     0.933333
20  84    -0.133332     3.333330    0.000003   0.450935     0.933333
21  85    -0.133332     3.333331    0.000007   0.050550     0.933333
22  86    -0.133333     3.333331    0.000002   0.450935     0.933333
23  87    -0.133333     3.333332    0.000004   0.050550     0.933333
24  88    -0.133333     3.333332    0.000001   0.450935     0.933333
25  89    -0.133333     3.333332    0.000003   0.050550     0.933333

In [5]:
Q=np.array([[20,5],[5,16]])
q=np.array([[-14],[-6]])
b=np.array([[10]])
-np.linalg.inv(Q).dot(q)

array([[0.65762712],
       [0.16949153]])

<h3>Inner Product Spaces</h3>
Throughout this file we assume that
<ul>
    <li>The matrix $Q$ is a positive definite symmetric matrix.</li>
    <li>The inner product notation
$$
<{\bf x},{\bf y}>_{Q}={\bf x}^tQ {\bf y}.
$$
where ${\bf x}$ and ${\bf y}$ are $n$-dimensional vectors.</li>
    <li>Some additional standard results from linear algebra.</li>
</ul>
<hr>

<h3>Theorem:</h3>
For all vectors ${\bf x}$, ${\bf y}$, ${\bf z}$, and all real number $\alpha$, we have
<ol>
    <li>$<{\bf x}, {\bf y}>_Q=<{\bf y},{\bf x}>_Q$</li>
    <li>$<\alpha {\bf x}, {\bf y}>_Q=\alpha<{\bf x},{\bf y}>_Q=<{\bf x},\alpha {\bf y}>_Q$</li>
    <li>$<{\bf x}+{\bf z}, {\bf y}>_Q=<{\bf x},{\bf y}>_Q+<{\bf z},{\bf y}>_Q$</li>
    <li>$<{\bf x},{\bf x}>_Q\geq 0$</li>
    <li>$<{\bf x}, {\bf x}>_{Q}=0$ if and only if ${\bf x}=0$.</li>
</ol>
WLOG, assume $<{\bf x},{\bf y}>=<{\bf x},{\bf y}>_{I}$ where $I$ is the identity matrix.
<hr>

<h3>Definition:</h3>
Let $\{{\bf d}^{1}, {\bf d}^{2}, \cdots,{\bf d}^{n}\}$ be satisfied
$$
<{\bf d}^{i},{\bf d}^{j}>_{Q}=0,\hbox{ if } i\neq j.
$$
The set of vectors $\{{\bf d}^{1}, {\bf d}^{2}, \cdots,{\bf d}^{n}\}$ is said to be $Q$-orthogonal.
<hr>
    <h3>Theorem:</h3>
    If $Q$ is positive definite and the set of vectors $\{{\bf d}^{1}, {\bf d}^{2}, \cdots,{\bf d}^{n}\}$ is $Q$-orthogonal, then it is linearly independent.
<hr>

In [13]:
Q=np.array([[4,3,0],[3,4,-1],[0,-1,4]])
d1=np.array([[1],[0],[0]])
d2=np.array([[-3/4],[1],[0]])
d3=np.array([[-3/7],[4/7],[1]])
print(d1.transpose().dot(Q).dot(d2)[0,0])
print(d1.transpose().dot(Q).dot(d3)[0,0])
print(d2.transpose().dot(Q).dot(d3)[0,0])

0.0
0.0
0.0


<h3>Example of Steepest Descent</h3>
Suppose that we seek to minimize
    $$f({\bf x}) = \displaystyle \frac{1}{2}{\bf x}^{t}Q{\bf x} +{\bf q}^{t}{\bf x} ,$$
    where
    \[
    Q = \left[
    \begin{array}{ccc}
        4 & 3 & 0 \\
        3 & 4 & -1 \\
        0 & -1 & 4
    \end{array}
    \right] \hbox{ and }
    {\bf q} = \left[
    \begin{array}{c}
        -24 \\
        -30 \\
        24
    \end{array}
    \right].
    \]
    Implement the CG on this problem, using the following starting points: ${\bf x}^{1} = (0,0,0)^{t}$.
    As it turns out, the optimal solution to this problem is ${\bf x}^{*} = (3,4,-5)^{t}$.
    


In [16]:
Q=np.array([[4,3,0],[3,4,-1],[0,-1,4]])
q=np.array([[-24],[-30],[24]])
f0=np.array([[0]])
xk=[np.array([[0],[0],[0]])]
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
dk=[]
alphak=[]
#dk.append
dk.append(-functionGradient(xk[k],Q,q))
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    #print("%d Step:" % k)
    #alphak.append
    alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    #print(dk[k])
    xk.append(xk[k]+alphak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0],xk[-1][2,0]))

No,xk0,xk1,xk2,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[],[]#empty list
for i in range(10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    xk2.append(xk[i][2,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
for i in range(19,len(alphak),10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    xk2.append(xk[i][2,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
finalSeg=i+1
for i in range(finalSeg,len(alphak)):    
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    xk2.append(xk[i][2,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"$x_{3}^{k}$":xk2,"norm":norm_d0,"Step Size":alphak0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

The optimal value is reported as -154.422792
An optimal solution is given by (3.153002,4.205419,-4.124940)


k  $x_{1}^{k}$  $x_{2}^{k}$  $x_{3}^{k}$       norm     Step Size  \
0     1     0.000000     0.000000     0.000000  45.299007  1.443662e-01   
1     2     3.464789     4.330986    -3.464789   6.579417  9.309348e-02   
2     3     3.199276     4.220847    -4.005649   4.059473  3.039039e-02   
3     4     3.154916     4.206051    -4.119812   3.561815  1.550605e-03   
4     5     3.152997     4.205417    -4.124952   3.539582 -3.695738e-06   
5     6     3.153002     4.205419    -4.124940   3.539635  1.689607e-08   
6     7     3.153002     4.205419    -4.124940   3.539634 -7.715601e-11   
7     8     3.153002     4.205419    -4.124940   3.539634  3.507992e-13   
8     9     3.153002     4.205419    -4.124940   3.539634 -1.467779e-15   
9    10     3.153002     4.205419    -4.124940   3.539634 -7.338896e-16   
10   20     3.153002     4.205419    -4.124940   3.539634  2.201669e-15   
11   30     3.153002     4.205419    -4.124940   3.539634 -1.467779e-15   
12   40     3.153002     4.205419    -4.124940   3.539634 -7.338896e-16   
13   50     3.153002     4.205419    -4.124940   3.539634  2.201669e-15   
14   60     3.153002     4.205419    -4.124940   3.539634 -1.467779e-15   
15   70     3.153002     4.205419    -4.124940   3.539634 -7.338896e-16   
16   80     3.153002     4.205419    -4.124940   3.539634  2.201669e-15   
17   90     3.153002     4.205419    -4.124940   3.539634 -1.467779e-15   
18  100     3.153002     4.205419    -4.124940   3.539634 -7.338896e-16   
19  101     3.153002     4.205419    -4.124940   3.539634  2.201669e-15   

           函數值  
0     0.000000  
1  -150.681710  
2  -153.933134  
3  -154.403227  
4  -154.422838  
5  -154.422792  
6  -154.422792  
7  -154.422792  
8  -154.422792  
9  -154.422792  
10 -154.422792  
11 -154.422792  
12 -154.422792  
13 -154.422792  
14 -154.422792  
15 -154.422792  
16 -154.422792  
17 -154.422792  
18 -154.422792  
19 -154.422792

In [17]:
Q=np.array([[4,3,0],[3,4,-1],[0,-1,4]])
q=np.array([[-24],[-30],[24]])
x=-np.linalg.inv(Q).dot(q)
print("But the objective value of (%.6f,%.6f,%.6f) is %.6f."%(x[0,0],x[1,0],x[2,0],functionValue(x,Q,q,f0)))

But the objective value of (3.000000,4.000000,-5.000000) is -156.000000.


<h3>Convergence Theorem of CG Method:</h3>

Let $$\{{\rm {\bf d}}^{1}, {\rm {\bf d}}^{2}, \cdots,{\rm {\bf d}}^{n}\}$$ be an $Q$-orthogonal set of nonzero vectors associated with the positive
definite matrix $Q$, and let ${\bf x}^{1}$ be arbitrary. Define
$$
t^k=\frac{<{\rm {\bf d}}^{k},-(Q{\bf x}^{k}+{\bf q})>}{<{\rm {\bf d}}^{k},Q{\rm {\bf d}}^{k}>} \hbox{ and } {\bf x}^{k+1}={\bf x}^{k}+t^k{\rm {\bf d}}^{k},
$$
for $k = 1, 2,\cdots,n$. Then, assuming exact arithmetic, $Q{\bf x}^{(n+1)} + {\bf q}=0$. |

<h3>Example of CG Method</h3>
Suppose that we seek to minimize
    $$f({\bf x}) = \displaystyle \frac{1}{2}{\bf x}^{t}Q{\bf x} +{\bf q}^{t}{\bf x} ,$$
    where
    \[
    Q = \left[
    \begin{array}{ccc}
        4 & 3 & 0 \\
        3 & 4 & -1 \\
        0 & -1 & 4
    \end{array}
    \right] \hbox{ and }
    {\bf q} = \left[
    \begin{array}{c}
        -24 \\
        -30 \\
        24
    \end{array}
    \right].
    \]
    Implement the CG on this problem, using the following starting points: ${\bf x}^{1} = (0,0,0)^{t}$.
    As it turns out, the optimal solution to this problem is ${\bf x}^{*} = (3,4,-5)^{t}$.
    
Given
    $$
        {\bf x}^{1}=\left[\begin{array}{c}0\\0\\0\end{array}\right]
    $$
    \item Given
    $$
        {\bf d}^{1}=\left[\begin{array}{c}1\\0\\0\end{array}\right],{\bf d}^{2}=\left[\begin{array}{c}\frac{-3}{4}\\1\\0\end{array}\right],{\bf d}^{3}=\left[\begin{array}{c}\frac{-3}{7}\\\frac{4}{7}\\1\end{array}\right]
    $$
    \item Then computing the following
    $$
        {\bf r}^{1}=-(Q{\bf x}^{1}+{\bf q}),t^{1}=\frac{({\bf d}^{1})^t{\bf r}^{1}}{({\bf d}^{1})^tQ{\bf d}^{1}}, {\bf x}^{2}={\bf x}^{1}+t^1{\bf d}^{1},
    $$
    $$
         {\bf r}^{2}=-(Q{\bf x}^{2}+{\bf q}),t^{2}=\frac{({\bf d}^{2})^t{\bf r}^{2}}{({\bf d}^{2})^tQ{\bf d}^{2}}, {\bf x}^{3}={\bf x}^{2}+t^2{\bf d}^{2},
    $$
    $$
         {\bf r}^{3}=-(Q{\bf x}^{3}+{\bf q}),t^{3}=\frac{({\bf d}^{3})^t{\bf r}^{3}}{({\bf d}^{3})^tQ{\bf d}^{3}}, {\bf x}^{4}={\bf x}^{3}+t^3{\bf d}^{3},
    $$ 

Define $f(x)=\frac{1}{2}{\bf x}^t Q {\bf x}^t +{\bf q}^t x$. Then the minimum of $f$ occurs on $\left\{x|Q{\bf x}+{\bf q}={\bf 0}\right\}$. Since $Q$ is positive-definite, $-Q^{-1}{\bf q}$ is the minimum point.

In [24]:
#######################################
Q=np.array([[4,3,0],[3,4,-1],[0,-1,4]])
q=np.array([[-24],[-30],[24]])
f0=np.array([[0]])
x1=np.array([[0],[0],[0]])
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
########################################
d1=np.array([[1],[0],[0]])
d2=np.array([[-3/4],[1],[0]])
d3=np.array([[-3/7],[4/7],[1]])
#################################
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d
print(x1)
#######################
r1=-functionGradient(x1,Q,q)
t1=d1.transpose().dot(r1)/(d1.transpose().dot(Q).dot(d1))
x2=x1+t1*d1
print(x2)
#######################
r2=-functionGradient(x2,Q,q)
t2=d2.transpose().dot(r2)/(d2.transpose().dot(Q).dot(d2))
x3=x2+t2*d2
print(x3)
#######################
r3=-functionGradient(x3,Q,q)
t3=d3.transpose().dot(r3)/(d3.transpose().dot(Q).dot(d3))
x4=x3+t3*d3
print(x4)

[[0]
 [0]
 [0]]
[[6.]
 [0.]
 [0.]]
[[0.85714286]
 [6.85714286]
 [0.        ]]
[[ 3.]
 [ 4.]
 [-5.]]


In [26]:
#######################################
Q=np.array([[4,3,0],[3,4,-1],[0,-1,4]])
q=np.array([[-24],[-30],[24]])
f0=np.array([[0]])
x1=np.array([[random.randint(-1000, 1000)],[random.randint(-1000, 1000)],[random.randint(-1000, 1000)]])
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
########################################
d1=np.array([[1],[0],[0]])
d2=np.array([[-3/4],[1],[0]])
d3=np.array([[-3/7],[4/7],[1]])
#################################
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d
print(x1)
#######################
r1=-functionGradient(x1,Q,q)
t1=d1.transpose().dot(r1)/(d1.transpose().dot(Q).dot(d1))
x2=x1+t1*d1
print(x2)
#######################
r2=-functionGradient(x2,Q,q)
t2=d2.transpose().dot(r2)/(d2.transpose().dot(Q).dot(d2))
x3=x2+t2*d2
print(x3)
#######################
r3=-functionGradient(x3,Q,q)
t3=d3.transpose().dot(r3)/(d3.transpose().dot(Q).dot(d3))
x4=x3+t3*d3
print(x4)

[[154]
 [761]
 [833]]
[[-564.75]
 [ 761.  ]
 [ 833.  ]]
[[-356.14285714]
 [ 482.85714286]
 [ 833.        ]]
[[ 3.]
 [ 4.]
 [-5.]]


https://en.wikipedia.org/wiki/Conjugate_gradient_method

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/021e02360a28c46188bc915eb06533dfa84a3002" with="600" heigh="400" alt="一張圖片">