In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<img src="http://140.116.53.170/classes/numericalOptimization/InteriorPointMethods/figure000.png" with="600" heigh="400">

In [2]:
m,n=2,4
A=np.zeros((m,n))
A[0,0]=1
A[0,1]=-2
A[0,2]=-1
A[0,3]=0
A[1,0]=-1
A[1,1]=-1
A[1,2]=0
A[1,3]=-1
b=np.zeros((m,1))
b[0,0]=-4
b[1,0]=-4
c=np.zeros((n,1))
c[0,0]=-1
c[1,0]=-3
c[2,0]=0
c[3,0]=0

<img src="http://140.116.53.170/classes/numericalOptimization/InteriorPointMethods/figure001.png" with="600" heigh="400">

In [3]:
barx=np.zeros((n,1))
barx[0,0]=1
barx[1,0]=1
barx[2,0]=4
barx[3,0]=4
r1=b-A.dot(barx)
print(r1)
bary=np.zeros((m,1))
bary[0,0]=1
bary[1,0]=1
bars=np.zeros((n,1))
bars[0,0]=1
bars[1,0]=1
bars[2,0]=1
bars[3,0]=1
r2=c-A.transpose().dot(bary)-bars
print(r2)
e=np.ones((n,1))
mu=100
print(mu*e)
barX=np.zeros((n,n))
barX[0,0]=barx[0,0]
barX[1,1]=barx[1,0]
barX[2,2]=barx[2,0]
barX[3,3]=barx[3,0]
for i in range(n):
    barX[i,i]=barx[i,0]
print(barX)
barS=np.zeros((n,n))
for i in range(n):
    barS[i,i]=bars[i,0]
print(barS)
r3=mu*e-barX.dot(barS).dot(e)
print(r3)

[[1.]
 [2.]]
[[-2.]
 [-1.]
 [ 0.]
 [ 0.]]
[[100.]
 [100.]
 [100.]
 [100.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 4.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[99.]
 [99.]
 [96.]
 [96.]]


<img src="http://140.116.53.170/classes/numericalOptimization/InteriorPointMethods/figure008.png" with="600" heigh="400">

In [4]:
r=np.vstack((r1,r2,r3))
print(r)
print(np.linalg.norm(r))
barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
print(barA)
np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))
barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
print(barA)
np.hstack((barS,np.zeros((n,m)),barX))
barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))
print(barA)
np.linalg.inv(barA)
DeltaX=np.linalg.inv(barA).dot(r)
print(DeltaX)
Deltax=DeltaX[0:n,:]
print(Deltax)
Deltay=DeltaX[n:n+m,:]
Deltas=DeltaX[n+m:2*n+m,:]
print(Deltay)
print(Deltas)
alphax=0.01
alphay=0.01
newx=barx+alphax*Deltax
newy=bary+alphay*Deltay
news=bars+alphay*Deltas#note alpahy
###############################################
barx=newx
bary=newy
bars=news
r1=b-A.dot(barx)
r2=c-A.transpose().dot(bary)-bars

barX=np.zeros((n,n))
for i in range(n):
    barX[i,i]=barx[i,0]
barS=np.zeros((n,n))
for i in range(n):
    barS[i,i]=bars[i,0]
r3=mu*e-barX.dot(barS).dot(e)

r=np.vstack((r1,r2,r3))
barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))

print(np.linalg.norm(r))

[[ 1.]
 [ 2.]
 [-2.]
 [-1.]
 [ 0.]
 [ 0.]
 [99.]
 [99.]
 [96.]
 [96.]]
195.0487118644981
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]]
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -2. -1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  1.]]
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -2. -1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  4.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  4.]]
[[ 70.47169811]
 [ 19.83018868]
 [ 29.81132075]
 [-92.30188679]
 [ 16.54716981]
 [ 47.0754717 ]
 [ 28.52830189]
 [ 79.16981132]
 [ 16.

The standard form of the given LP
$$
\begin{array}{rl}
\min & -x_1-3x_2\\
s.t. & x_1-2x_2 \geq -4\\
     & -x_1-x_2\geq -4\\
     &x_1,x_2\geq 0
\end{array}
$$
is 
$$
\begin{array}{rl}
\min & -x_1-3x_2\\
s.t. & x_1-2x_2-x_3 =-4\\
     & -x_1-x_2-x_4 =-4\\
     &x_1,x_2,x_3,x_4\geq 0
\end{array}.
$$

In [22]:
d=np.array([[1],[-1],[2],[-2]])
x=np.array([[1],[1/2],[1/3],[1/4]])
epsilon=1e-8
gamma=0.9
def determineStepSizeUB(d,x,gamma):
    alphaUB=float("inf")
    n=len(x)
    for i in range(n):
        if d[i,0]<0:
            if alphaUB>-(gamma*x[i,0])/d[i,0]:
                alphaUB=-(gamma*x[i,0])/d[i,0]
    return (alphaUB)

alphaUB = detrmineStepSizeUB(d,x,gamma)
print(alphaUB)
print(x+alphaUB*d)

0.1125
[[1.1125    ]
 [0.3875    ]
 [0.55833333]
 [0.025     ]]


In [23]:
d=np.array([[1],[-1],[2],[-2]])
x=np.array([[1],[1/2],[1/3],[1/4]])
epsilon=1e-8
gamma=0.9
def determineStepSizeUB(d,x,gamma,UB=1):#default UB=1
    alphaUB=float("inf")
    n=len(x)
    for i in range(n):
        if d[i,0]<0:
            if alphaUB>-(gamma*x[i,0])/d[i,0]:
                alphaUB=-(gamma*x[i,0])/d[i,0]
    if alphaUB>UB:
        alphaUB=UB
    return alphaUB

alphaUB = detrmineStepSizeUB(d,x,gamma,0.1)#can insert new UB
print(alphaUB)
print(x+alphaUB*d)

0.1
[[1.1       ]
 [0.4       ]
 [0.53333333]
 [0.05      ]]


In [24]:
m,n=2,4
A=np.zeros((m,n))
A[0,0]=1
A[0,1]=-2
A[0,2]=-1
A[0,3]=0
A[1,0]=-1
A[1,1]=-1
A[1,2]=0
A[1,3]=-1
b=np.zeros((m,1))
b[0,0]=-4
b[1,0]=-4
c=np.zeros((n,1))
c[0,0]=-1
c[1,0]=-3
c[2,0]=0
c[3,0]=0


barx=np.zeros((n,1))
barx[0,0]=1
barx[1,0]=1
barx[2,0]=4
barx[3,0]=4
r1=b-A.dot(barx)
print(r1)
bary=np.zeros((m,1))
bary[0,0]=1
bary[1,0]=1
bars=np.zeros((n,1))
bars[0,0]=1
bars[1,0]=1
bars[2,0]=1
bars[3,0]=1
r2=c-A.transpose().dot(bary)-bars
print(r2)
e=np.ones((n,1))
mu=100
print(mu*e)
barX=np.zeros((n,n))
barX[0,0]=barx[0,0]
barX[1,1]=barx[1,0]
barX[2,2]=barx[2,0]
barX[3,3]=barx[3,0]
for i in range(n):
    barX[i,i]=barx[i,0]
print(barX)
barS=np.zeros((n,n))
for i in range(n):
    barS[i,i]=bars[i,0]
print(barS)
r3=mu*e-barX.dot(barS).dot(e)
print(r3)
r=np.vstack((r1,r2,r3))
print(r)
print(np.linalg.norm(r))

barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
print(barA)
np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))
barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
print(barA)
np.hstack((barS,np.zeros((n,m)),barX))
barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))
print(barA)
np.linalg.inv(barA)
DeltaX=np.linalg.inv(barA).dot(r)
print(DeltaX)
Deltax=DeltaX[0:n,:]
print(Deltax)
Deltay=DeltaX[n:n+m,:]
Deltas=DeltaX[n+m:2*n+m,:]
print(Deltay)
print(Deltas)
alphax=0.01


gamma=0.9
alphax = determineStepSizeUB(Deltax,barx,gamma)
print(alphax)
alphay=0.01
alphay = determineStepSizeUB(Deltas,bars,gamma)
print(alphay)


newx=barx+alphax*Deltax
newy=bary+alphay*Deltay
news=bars+alphay*Deltas#note alpahy
###############################################
barx=newx
bary=newy
bars=news
r1=b-A.dot(barx)
r2=c-A.transpose().dot(bary)-bars

barX=np.zeros((n,n))
for i in range(n):
    barX[i,i]=barx[i,0]
barS=np.zeros((n,n))
for i in range(n):
    barS[i,i]=bars[i,0]
r3=mu*e-barX.dot(barS).dot(e)

r=np.vstack((r1,r2,r3))
barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))

print(np.linalg.norm(r))

[[1.]
 [2.]]
[[-2.]
 [-1.]
 [ 0.]
 [ 0.]]
[[100.]
 [100.]
 [100.]
 [100.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 4.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[99.]
 [99.]
 [96.]
 [96.]]
[[ 1.]
 [ 2.]
 [-2.]
 [-1.]
 [ 0.]
 [ 0.]
 [99.]
 [99.]
 [96.]
 [96.]]
195.0487118644981
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]]
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -2. -1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  1.]]
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -2. -1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  0. 

In [25]:
m,n=2,4
A=np.zeros((m,n))
A[0,0]=1
A[0,1]=-2
A[0,2]=-1
A[0,3]=0
A[1,0]=-1
A[1,1]=-1
A[1,2]=0
A[1,3]=-1
b=np.zeros((m,1))
b[0,0]=-4
b[1,0]=-4
c=np.zeros((n,1))
c[0,0]=-1
c[1,0]=-3
c[2,0]=0
c[3,0]=0


barx=np.zeros((n,1))
barx[0,0]=1
barx[1,0]=1
barx[2,0]=4
barx[3,0]=4
r1=b-A.dot(barx)
#print(r1)
bary=np.zeros((m,1))
bary[0,0]=1
bary[1,0]=1
bars=np.zeros((n,1))
bars[0,0]=1
bars[1,0]=1
bars[2,0]=1
bars[3,0]=1

r2=c-A.transpose().dot(bary)-bars
#print(r2)
e=np.ones((n,1))
mu=100




i=0
while i<=5:
    #print(mu*e)
    barX=np.zeros((n,n))
    barX[0,0]=barx[0,0]
    barX[1,1]=barx[1,0]
    barX[2,2]=barx[2,0]
    barX[3,3]=barx[3,0]
    for i in range(n):
        barX[i,i]=barx[i,0]
    #print(barX)
    barS=np.zeros((n,n))
    for i in range(n):
        barS[i,i]=bars[i,0]
    #print(barS)
    r3=mu*e-barX.dot(barS).dot(e)
    #print(r3)


    r=np.vstack((r1,r2,r3))

    #print(r)
    #print(np.linalg.norm(r))

    barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
    #print(barA)
    np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))
    barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
    #print(barA)
    np.hstack((barS,np.zeros((n,m)),barX))
    barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))
    #print(barA)
    np.linalg.inv(barA)
    DeltaX=np.linalg.inv(barA).dot(r)
    #print(DeltaX)
    Deltax=DeltaX[0:n,:]
    #print(Deltax)
    Deltay=DeltaX[n:n+m,:]
    Deltas=DeltaX[n+m:2*n+m,:]
    #print(Deltay)
    #print(Deltas)
    alphax=0.01


    gamma=0.9
    alphax = determineStepSizeUB(Deltax,barx,gamma)
    #print(alphax)
    alphay=0.01
    alphay = determineStepSizeUB(Deltas,bars,gamma)
    #print(alphay)


    newx=barx+alphax*Deltax
    newy=bary+alphay*Deltay
    news=bars+alphay*Deltas#note alpahy
###############################################
    barx=newx
    bary=newy
    bars=news
    print(np.linalg.norm(r))
    i=i+1


195.0487118644981
92.27834595956352
60.78820849450314
77.0669627771834
82.60518243173891
53.571666646782
121.46035431263186
1358.9179460274047
79737.97312381759
41974785.115199775
220509883600.61758
1.1584197481340968e+16
6.085606186730335e+21
3.196993379957712e+28
1.6794985343908408e+36
8.823025235849246e+44
4.6350605682824956e+54
2.434968267386964e+65
1.2791786376544512e+77
6.719997171821284e+89
3.5302623621115197e+103
1.8545770223834069e+118
9.742777105935232e+133
5.118240148039088e+150
inf
inf
inf
inf
inf
inf


LinAlgError: Singular matrix

In [26]:
m,n=2,4
A=np.zeros((m,n))
A[0,0]=1
A[0,1]=-2
A[0,2]=-1
A[0,3]=0
A[1,0]=-1
A[1,1]=-1
A[1,2]=0
A[1,3]=-1
b=np.zeros((m,1))
b[0,0]=-4
b[1,0]=-4
c=np.zeros((n,1))
c[0,0]=-1
c[1,0]=-3
c[2,0]=0
c[3,0]=0


barx=np.zeros((n,1))
barx[0,0]=1
barx[1,0]=1
barx[2,0]=4
barx[3,0]=4
r1=b-A.dot(barx)
#print(r1)
bary=np.zeros((m,1))
bary[0,0]=1
bary[1,0]=1
bars=np.zeros((n,1))
bars[0,0]=1
bars[1,0]=1
bars[2,0]=1
bars[3,0]=1

r2=c-A.transpose().dot(bary)-bars
#print(r2)
e=np.ones((n,1))
mu=100




iteration=0
while iteration<=5:
    
    #print(mu*e) 
    print(iteration)
    r1=b-A.dot(barx)
    r2=c-A.transpose().dot(bary)-bars
    barX=np.zeros((n,n))
    barX[0,0]=barx[0,0]
    barX[1,1]=barx[1,0]
    barX[2,2]=barx[2,0]
    barX[3,3]=barx[3,0]
    for i in range(n):
        barX[i,i]=barx[i,0]
    #print(barX)
    barS=np.zeros((n,n))
    for i in range(n):
        barS[i,i]=bars[i,0]
    #print(barS)
    r3=mu*e-barX.dot(barS).dot(e)
    #print(r3)


    r=np.vstack((r1,r2,r3))

    #print(r)
    #print(np.linalg.norm(r))

    barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
    #print(barA)
    np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))
    barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
    #print(barA)
    np.hstack((barS,np.zeros((n,m)),barX))
    barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))
    #print(barA)
    np.linalg.inv(barA)
    DeltaX=np.linalg.inv(barA).dot(r)
    #print(DeltaX)
    Deltax=DeltaX[0:n,:]
    #print(Deltax)
    Deltay=DeltaX[n:n+m,:]
    Deltas=DeltaX[n+m:2*n+m,:]
    #print(Deltay)
    #print(Deltas)
    alphax=0.01


    gamma=0.9
    alphax = determineStepSizeUB(Deltax,barx,gamma)
    #print(alphax)
    alphay=0.01
    alphay = determineStepSizeUB(Deltas,bars,gamma)
    #print(alphay)


    newx=barx+alphax*Deltax
    newy=bary+alphay*Deltay
    news=bars+alphay*Deltas#note alpahy
###############################################
    barx=newx
    bary=newy
    bars=news
    print(np.linalg.norm(r))
    mu=barx.transpose().dot(bars)/(10*n)
    iteration = iteration+1
print(barx)

0
195.0487118644981
1
186.54435231826696
2
49.83470614692771
3
6.517018541382946
4
2.123219791847234
5
0.6624719949946216
[[1.31056695]
 [2.64114274]
 [0.02828146]
 [0.0482903 ]]


In [27]:
m,n=2,4
A=np.zeros((m,n))
A[0,0]=1
A[0,1]=-2
A[0,2]=-1
A[0,3]=0
A[1,0]=-1
A[1,1]=-1
A[1,2]=0
A[1,3]=-1
b=np.zeros((m,1))
b[0,0]=-4
b[1,0]=-4
c=np.zeros((n,1))
c[0,0]=-1
c[1,0]=-3
c[2,0]=0
c[3,0]=0


barx=np.zeros((n,1))
barx[0,0]=1
barx[1,0]=1
barx[2,0]=4
barx[3,0]=4
r1=b-A.dot(barx)
#print(r1)
bary=np.zeros((m,1))
bary[0,0]=1
bary[1,0]=1
bars=np.zeros((n,1))
bars[0,0]=1
bars[1,0]=1
bars[2,0]=1
bars[3,0]=1


#print(r2)
e=np.ones((n,1))
mu=100

r1=b-A.dot(barx)
r2=c-A.transpose().dot(bary)-bars
barX=np.zeros((n,n))
barX[0,0]=barx[0,0]
barX[1,1]=barx[1,0]
barX[2,2]=barx[2,0]
barX[3,3]=barx[3,0]
for i in range(n):
    barX[i,i]=barx[i,0]
#print(barX)
barS=np.zeros((n,n))
for i in range(n):
    barS[i,i]=bars[i,0]
#print(barS)
r3=mu*e-barX.dot(barS).dot(e)
r=np.vstack((r1,r2,r3))

iteration=0
while iteration<=100 and np.linalg.norm(r)>1e-6:
    
    #print(mu*e) 
    print(iteration)
   
    #print(r3)


    r=np.vstack((r1,r2,r3))

    #print(r)
    #print(np.linalg.norm(r))

    barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
    #print(barA)
    np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))
    barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
    #print(barA)
    np.hstack((barS,np.zeros((n,m)),barX))
    barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))
    #print(barA)
    np.linalg.inv(barA)
    DeltaX=np.linalg.inv(barA).dot(r)
    #print(DeltaX)
    Deltax=DeltaX[0:n,:]
    #print(Deltax)
    Deltay=DeltaX[n:n+m,:]
    Deltas=DeltaX[n+m:2*n+m,:]
    #print(Deltay)
    #print(Deltas)
    alphax=0.01


    gamma=0.9
    alphax = determineStepSizeUB(Deltax,barx,gamma)
    #print(alphax)
    alphay=0.01
    alphay = determineStepSizeUB(Deltas,bars,gamma)
    #print(alphay)


    newx=barx+alphax*Deltax
    newy=bary+alphay*Deltay
    news=bars+alphay*Deltas#note alpahy
###############################################
    barx=newx
    bary=newy
    bars=news
    print(np.linalg.norm(r))
    mu=barx.transpose().dot(bars)/(10*n)
    iteration = iteration+1
    r1=b-A.dot(barx)
    r2=c-A.transpose().dot(bary)-bars
    barX=np.zeros((n,n))
    barX[0,0]=barx[0,0]
    barX[1,1]=barx[1,0]
    barX[2,2]=barx[2,0]
    barX[3,3]=barx[3,0]
    for i in range(n):
        barX[i,i]=barx[i,0]
    #print(barX)
    barS=np.zeros((n,n))
    for i in range(n):
        barS[i,i]=bars[i,0]
    #print(barS)
    r3=mu*e-barX.dot(barS).dot(e)
    r=np.vstack((r1,r2,r3))
    
print(barx)

0
195.0487118644981
1
186.54435231826696
2
49.83470614692771
3
6.517018541382946
4
2.123219791847234
5
0.6624719949946216
6
0.09983306064443273
7
0.011394214641513507
8
0.0012580177246344065
9
0.00013456054553563377
10
1.3956622004840039e-05
11
1.4218404900786894e-06
[[1.33333334e+00]
 [2.66666661e+00]
 [1.20725053e-07]
 [4.82903030e-08]]


There are $4$ data points $(x_1,y_1)$, $(x_2,y_2)$, $(x_3,y_3)$, $(x_{4},y_{4})$:
$$
\begin{array}{|r|r|r|r|r|r|r|r|r|r|r|r|r||r|r|r|}
\hline
   i  & 1 & 2 & 3 & 4 \\\hline
  x_i & 4.0 & 4.2 & 4.5 & 4.7 \\ \hline
  y_i & 102.56 & 113.18 & 130.11 & 142.05 \\
  \hline
\end{array}
$$
Assume that the curve $f(x)$ is defined by $(\alpha_1,\alpha_2,\alpha_{3})$ i.e.
$f(x)=\alpha_{3} x^{2} + \alpha_{2} x^{1} + \alpha_{1}.$ Here, we consider the fitting problem:
$$
(P_1)
\begin{array}{rl}
\min & \sum_{i=1}^{4} |y_{i}-f(x_i)|\\
s.t. & \alpha_1,\alpha_2,\alpha_{3}: unrestricted.
\end{array}
$$
For the problem $(P_1)$, we reformulate it as follows
$$
\begin{array}{rl}
\min & \sum_{i=1}^{4} t_i+s_i\\
s.t. & y_i-f(x_i)=t_i-s_i, i=1,2,3,4\\
     & \alpha_1,\alpha_2,\alpha_3: unrestricted.\\
     & t_i\geq 0, i=1,2,3,4\\
     & s_i\geq 0, i=1,2,3,4
\end{array}
$$
Build a py-file to solve the problem $(P_1)$.

In [35]:
dataSet=[[4.0,102.56],[4.2,113.18],[4.5,130.11],[4.7,142.05]]
dataSet=np.array(dataSet)
print(dataSet)
numberDatapts=len(dataSet)
dimDatapt=len(dataSet[0,:])
print(numberDatapts,dimDatapt)


[[  4.   102.56]
 [  4.2  113.18]
 [  4.5  130.11]
 [  4.7  142.05]]
4 2


In [38]:
degree=3
A=np.zeros((numberDatapts,2*degree+2*numberDatapts))
print(A)
for i in range(numberDatapts):
    A[0,0]=1
    A[0,1]=-1
    A[0,2]=dataSet[i,0]
    A[0,3]=-dataSet[i,0]
    A[0,4]=(dataSet[i,0])**2
    A[0,5]=-(dataSet[i,0])**2
    A[0,6]=1
    A[0,7]=-1
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[  1.    -1.     4.7   -4.7   22.09 -22.09   1.    -1.     0.     0.
    0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.  ]]


In [41]:
degree=3
A=np.zeros((numberDatapts,2*degree+2*numberDatapts))
print(A)
for i in range(numberDatapts):
    A[0,0]=1
    A[0,1]=-1
    A[0,2]=dataSet[i,0]
    A[0,3]=-dataSet[i,0]
    A[0,4]=(dataSet[i,0])**2
    A[0,5]=-(dataSet[i,0])**2
    A[i,5+i*2+1]=1
    A[i,6+i*2+1]=-1
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[  1.    -1.     4.7   -4.7   22.09 -22.09   1.    -1.     0.     0.
    0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     1.    -1.
    0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    1.    -1.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     1.    -1.  ]]


In [44]:
degree=3
A=np.zeros((numberDatapts,2*degree+2*numberDatapts))
print(A)
for i in range(numberDatapts):
    print(i)
    A[i,0*2]=1
    A[i,0*2+1]=-1
    for j in range(1,degree): 
        A[i,j*2]=(dataSet[i,0])**j
        A[i,j*2+1]=-(dataSet[i,0])**j
    A[i,5+i*2+1]=1
    A[i,6+i*2+1]=-1
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0
1
2
3
[[  1.    -1.     4.    -4.    16.   -16.     1.    -1.     0.     0.
    0.     0.     0.     0.  ]
 [  1.    -1.     4.2   -4.2   17.64 -17.64   0.     0.     1.    -1.
    0.     0.     0.     0.  ]
 [  1.    -1.     4.5   -4.5   20.25 -20.25   0.     0.     0.     0.
    1.    -1.     0.     0.  ]
 [  1.    -1.     4.7   -4.7   22.09 -22.09   0.     0.     0.     0.
    0.     0.     1.    -1.  ]]


In [49]:
b=np.zeros((numberDatapts,1))
for i in range(numberDatapts):
    b[i,0]=dataSet[i,1]
print(b)
c=np.zeros((2*degree+2*numberDatapts,1))
for i in range(numberDatapts):
    c[2*degree+i*2,0]=1
    c[2*degree+i*2+1,0]=1
print(c)

[[102.56]
 [113.18]
 [130.11]
 [142.05]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
