In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

$$
\begin{array}{rl}
\max & 4y_1+4y_2\\
s.t. & y_1-y_2 \leq -1\\
     & -2y_1-y_2\leq -3\\
     &y_1,y_2\geq 0
\end{array}
$$

The KKT condition of
$$
\begin{array}{rl}
\min & -x_1-3x_2\\
s.t. & x_1-2x_2 \geq -4\\
     & -x_1-x_2\geq -4\\
     &x_1,x_2\geq 0
\end{array}
$$
is given by $$
\begin{array}{l}
(P)\left\{
\begin{array}{l}
\color{red}{x_1-2x_2-x_3=-4}\\
\color{red}{-x_1-x_2-x_4= -4}\\
x_1,x_2,x_3,x_4\geq 0\\
\end{array}
\right.\\
(D)\left\{
\begin{array}{l}
\color{red}{y_1-y_2+y_3 =-1}\\
\color{red}{-2y_1-y_2+y_4 =-3}\\
y_1,y_2,y_3,y_4\geq 0\\
\end{array}
\right.\\
(CS)\left\{
\begin{array}{l}
{x_1=0\hbox{ or }y_3=0}\\
{x_2=0\hbox{ or }y_4=0}\\
{x_3=0\hbox{ or }y_1=0}\\
{x_4=0\hbox{ or }y_2=0}\\
\end{array}
\right.
\end{array}
$$


$$
\begin{array}{|c|c||c|c|c|c||c|c|c|c|c|}
\hline
\hbox{P} & \hbox{D} &x_1 & x_2 & x_3 & x_4 & y_1 & y_2 & y_3 & y_4 & reason\\ \hline
\times&      & 0  &  0  &  0  &  0  &     &     &     &     & x_1-2x_2-x_3=-4 \\ \hline
\times&      & 0  &  0  &  0  &     &     &  0  &     &     &x_1-2x_2-x_3=-4\\
\times&      & 0  &  0  &     &  0  &  0  &     &     &     &-x_1-x_2-x_4= -4\\
\times&      & 0  &     &  0  &  0  &     &     &     &  0  &x_2=2\quad and\quad x_2=4\\
\times&      &    &  0  &  0  &  0  &     &     &  0  &     &x_1=4\quad and\quad x_1=-4\\ \hline
\times&      & 0  &     &     &     &  0  &  0  &     &  0  &-2y_1-y_2+y_4 =-3\\
\times&      &    &  0  &     &     &  0  &  0  &  0  &     &y_1-y_2+y_3 =-1\\
\times&      &    &     &  0  &     &     &  0  &  0  &  0  &y_1=3/2 \quad and \quad y_1=-1\\
\times&      &    &     &     &  0  &  0  &     &  0  &  0  &y_2=3 \quad and \quad y_2=1\\\hline
\times&      &    &     &     &     &  0  &  0  &  0  &  0  &y_1-y_2+y_3 =-1\\
\hline
\end{array}
$$

$$
\begin{array}{|c|c||c|c|c|c||c|c|c|c|c|}
\hline
 & 
        &x_1   & x_2& x_3 & x_4 & y_1 & y_2 & y_3 & y_4 & reason\\ \hline
\hbox{A}&      & 0  &  0  &  4  & 4   &     &     &     &     & x_1-2x_2-x_3=-4, -x_1-x_2-x_4= -4\\
\hbox{B}&      & 0  &  2  &  0  & 2   &     &     &     &     &\\
\hbox{C}&      & 4  &  0  &  8  & 0   &     &     &     &     &\\
\hbox{D}&      & 4/3&  8/3&  0  & 0   &     &     &     &     &\\\hline
        &\hbox{E}&    &     &     &     & 0   & 3   & 2   & 0   &x_1-2x_2-x_3=-4, -x_1-x_2-x_4= -4\\
        &\hbox{F}&    &     &     &     & 2/3 &  5/3& 0   & 0   &-2y_1-y_2+y_4 =-3,y_1-y_2+y_3 =-1\\ \hline
\end{array}
$$

$$
\begin{array}{|c|c||c|c|c|c||c|c|c|c|c|}
\hline
 & 
        &x_1   & x_2& x_3 & x_4 & y_1 & y_2 & y_3 & y_4 & reason\\ \hline
\hbox{A}&\hbox{E}& 0  &  0  &  4  & 4   & 0   & 3   & 2   & 0   &x_4y_2\neq 0\\
\hbox{A}&\hbox{F}& 0  &  0  &  4  & 4   & 2/3 &  5/3& 0   & 0   &x_3y_1\neq 0 \\
\hbox{B}&\hbox{E}& 0  &  2  &  0  & 2   & 0   & 3   & 2   & 0   &x_4y_2\neq 0\\
\hbox{B}&\hbox{F}& 0  &  2  &  0  & 2   & 2/3 &  5/3& 0   & 0   &x_4y_2\neq 0\\
\hbox{C}&\hbox{E}& 4  &  0  &  8  & 0   & 0   & 3   & 2   & 0   &x_1y_3\neq 0 \\
\hbox{C}&\hbox{F}& 4  &  0  &  8  & 0   & 2/3 &  5/3& 0   & 0   &x_3y_1\neq 0\\
\hbox{D}&\hbox{E}& 4/3&  8/3&  0  & 0   & 0   & 3   & 2   & 0   &x_1y_3\neq 0 \\
\hbox{D}&\hbox{F}& 4/3&  8/3&  0  & 0   & 2/3 &  5/3& 0   & 0   &\\
\hline
\end{array}
$$

The KKT condition of
$$
\begin{array}{rl}
\min & -x_1-3x_2\\
s.t. & x_1-2x_2 \geq -4\\
     & -x_1-x_2\geq -4\\
     &x_1,x_2\geq 0
\end{array}
$$
is given by $$
\begin{array}{l}
(P)\left\{
\begin{array}{l}
\color{red}{x_1-2x_2-x_3=-4}\\
\color{red}{-x_1-x_2-x_4= -4}\\
x_1,x_2,x_3,x_4\geq 0\\
\end{array}
\right.\Rightarrow A{\bf x}={\bf b},{\bf x}\geq 0\\
(D)\left\{
\begin{array}{l}
\color{red}{y_1-y_2+y_3 =-1}\\
\color{red}{-2y_1-y_2+y_4 =-3}\\
y_1,y_2,y_3,y_4\geq 0\\
\end{array}
\right.\Rightarrow A^{t}{\bf y}={\bf c},{\bf x}\geq 0\\
(CS)\left\{
\begin{array}{l}
{x_1=0\hbox{ or }y_3=0}\\
{x_2=0\hbox{ or }y_4=0}\\
{x_3=0\hbox{ or }y_1=0}\\
{x_4=0\hbox{ or }y_2=0}\\
\end{array}
\right.
\end{array}
$$
Where
$$
{\bf x}=\left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
x_4\\
\end{array}\right],
{\bf x}=\left[\begin{array}{c}
y_1\\
y_2\\
y_3\\
y_4\\
\end{array}\right],
A=\left[\begin{array}{cccc}
1 & -2 & -1 & 0 \\
-1 & -1 & 0 & -1\\
\end{array}\right],
{\bf b}=\left[\begin{array}{cc}
-4\\
-4\\
\end{array}\right],
{\bf c}=\left[\begin{array}{cc}
-1\\
-3\\
\end{array}\right]
$$


$$
x_1y_3=0 \Rightarrow X^tQ_1 X=0
$$ 
where 
$$
X=\left[
\begin{array}{c}
x_1\\
x_2\\
x_3\\
x_4\\
y_1\\
y_2\\
y_3\\
y_4\\
\end{array}
\right],
Q_1=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &  0 &    0 &  1/2 & 0\\
 0 &  0 &  0 &  0 &  0 &   0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &   0 &  0 & 0\\
 1/2 &  0 &  0 &  0 &  0 & 0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &  0 &  0 & 0\\
\end{array}\right]
$$

$$
x_2y_4=0 \Rightarrow X^tQ_2 X=0
$$ 
where 
$$
X=\left[
\begin{array}{c}
x_1\\
x_2\\
x_3\\
x_4\\
y_1\\
y_2\\
y_3\\
y_4\\
\end{array}
\right],
Q_2=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 1/2\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  1/2 &  0 &  0 &    0 &  0 &  0 & 0\\
\end{array}\right]
$$

$$
x_3y_1=0 \Rightarrow X^tQ_3 X=0
$$ 
where 
$$
X=\left[
\begin{array}{c}
x_1\\
x_2\\
x_3\\
x_4\\
y_1\\
y_2\\
y_3\\
y_4\\
\end{array}
\right],
Q_3=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    1/2 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  1/2 &  0  &  0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
\end{array}\right]
$$

$$
x_4y_2=0 \Rightarrow X^tQ_4 X=0
$$ 
where 
$$
X=\left[
\begin{array}{c}
x_1\\
x_2\\
x_3\\
x_4\\
y_1\\
y_2\\
y_3\\
y_4\\
\end{array}
\right],
Q_4=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &   0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &   0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  1/2 &  0 & 0\\
 0 &  0 &  0 &  0 &   0 &  0 &  0 & 0\\
 0 &  0 &  0 &  1/2 &   0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &   0 &  0 &  0 & 0\\
 0 &  0 &  0 &  0 &    0 &  0 &  0 & 0\\
\end{array}\right]
$$

$$
x_1y_3=0,x_2y_4=0,x_3y_1=0,x_4y_2=0 \Rightarrow X^tQ_1 X=0,X^tQ_2 X=0,X^tQ_3 X=0,X^tQ_4 X=0
$$ 
where 
$$
X=\left[
\begin{array}{c}
x_1\\
x_2\\
x_3\\
x_4\\
y_1\\
y_2\\
y_3\\
y_4\\
\end{array}
\right],
Q_1=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &  0 &    0 & 1/2 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &    0 &  0 & 0\\
 1/2 &  0 &  0 &  0 &  0 &   0 &  0 & 0\\
 0 &  0 &  0 &  0 &  0 &   0 &  0 & 0\\
\end{array}\right],
Q_2=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &  0 &  0 &    0 & 0\\
 0 &  0 &  0 &  0 &  0 &  0 &    0 & 1/2\\
 0 &  0 &  0 &  0 &  0 &  0 &    0 & 0\\
 0 &  0 &  0 &  0 &  0 &  0 &    0 & 0\\
 0 &  0 &  0 &  0 &  0 &  0 &    0 & 0\\
 0 &  0 &  0 &  0 &  0 &  0 &    0 & 0\\
 0 &  0 &  0 &  0 &  0 &  0 &    0 & 0\\
 0 &  1/2 &  0 &  0 &  0 &   0 &  0 & 0\\
\end{array}\right],
$$
$$
Q_3=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  1/2 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  1/2 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
\end{array}\right]
Q_4=
\left[\begin{array}{cccc}
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  1/2 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0\\
 0 &  0 &  0 &  1/2 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 \\
\end{array}\right]
$$


In [2]:
m,n=2,2
Q1=np.zeros((2*(m+n),2*(m+n)))
Q1[0,6]=1/2
Q1[6,0]=1/2
Q2=np.zeros((2*(m+n),2*(m+n)))
Q2[1,7]=1/2
Q2[7,2]=1/2
Q3=np.zeros((2*(m+n),2*(m+n)))
Q3[2,4]=1/2
Q3[4,2]=1/2
Q4=np.zeros((2*(m+n),2*(m+n)))
Q4[3,5]=1/2
Q4[5,3]=1/2
print(Q1)
X=np.zeros((2*(m+n),1))
X[0,0]=4/3
X[1,0]=8/3
X[4,0]=2/3
X[5,0]=5/3
print(X.transpose().dot(Q1).dot(X),X.transpose().dot(Q2).dot(X),X.transpose().dot(Q3).dot(X),X.transpose().dot(Q4).dot(X),)


[[0.  0.  0.  0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]]
[[0.]] [[0.]] [[0.]] [[0.]]


In [3]:
m,n=2,2
i,j=1,3
Q1=np.zeros((2*(m+n),2*(m+n)))
Q1[i-1,j+3]=1/2
Q1[j+3,i-1]=1/2
i,j=2,4
Q2=np.zeros((2*(m+n),2*(m+n)))
Q2[i-1,j+3]=1/2
Q2[j+3,i-1]=1/2
i,j=3,1
Q3=np.zeros((2*(m+n),2*(m+n)))
Q3[i-1,j+3]=1/2
Q3[j+3,i-1]=1/2
i,j=4,2
Q4=np.zeros((2*(m+n),2*(m+n)))
Q4[i-1,j+3]=1/2
Q4[j+3,i-1]=1/2
X=np.zeros((2*(m+n),1))
X[0,0]=4/3
X[1,0]=8/3
X[4,0]=2/3
X[5,0]=5/3
print(X.transpose().dot(Q1).dot(X),X.transpose().dot(Q2).dot(X),X.transpose().dot(Q3).dot(X),X.transpose().dot(Q4).dot(X))

[[0.]] [[0.]] [[0.]] [[0.]]


In [4]:
m,n=2,2
X=np.zeros((2*(m+n),1))
X[0,0]=4/3
X[1,0]=8/3
X[4,0]=2/3
X[5,0]=5/3
for l in range(1,m+1):
    i=l
    j=m+1
    Q=np.zeros((2*(m+n),2*(m+n)))
    Q[i-1,j+3]=1/2
    Q[j+3,i-1]=1/2
    print(i,j)
    print(X.transpose().dot(Q).dot(X))
for l in range(1,m+1):
    i=n+1
    j=l
    Q=np.zeros((2*(m+n),2*(m+n)))
    Q[i-1,j+3]=1/2
    Q[j+3,i-1]=1/2
    print(i,j)
    print(X.transpose().dot(Q).dot(X))


1 3
[[0.]]
2 3
[[0.]]
3 1
[[0.]]
3 2
[[0.]]


In [5]:
m,n=2,2
X=np.zeros((2*(m+n),1))
X[0,0]=4/3
X[1,0]=8/3
X[4,0]=2/3
X[5,0]=5/3
Q=[[]]
for l in range(1,n+1):
    i=l
    j=m+l
    Ql=np.zeros((2*(m+n),2*(m+n)))
    Ql[i-1,j+n+m-1]=1/2
    Ql[j+n+m-1,i-1]=1/2
    Q.append(Ql)
    print(i,j)
    print(X.transpose().dot(Ql).dot(X))
for l in range(1,m+1):
    i=n+l
    j=l
    Ql=np.zeros((2*(m+n),2*(m+n)))
    Ql[i-1,j+n+m-1]=1/2
    Ql[j+n+m-1,i-1]=1/2
    Q.append(Ql)
    print(i,j)
    print(X.transpose().dot(Ql).dot(X))
print(Q[1])

1 3
[[0.]]
2 4
[[0.]]
3 1
[[0.]]
4 2
[[0.]]
[[0.  0.  0.  0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]]


$$\begin{array}{l}
(P)\left\{
\begin{array}{l}
\color{red}{x_1-2x_2-x_3=-4}\\
\color{red}{-x_1-x_2-x_4= -4}\\
x_1,x_2,x_3,x_4\geq 0\\
\end{array}
\right.\Rightarrow [A, -I]{\bf x}={\bf b},{\bf x}\geq 0\\
(D)\left\{
\begin{array}{l}
\color{red}{y_1-y_2+y_3 =-1}\\
\color{red}{-2y_1-y_2+y_4 =-3}\\
y_1,y_2,y_3,y_4\geq 0\\
\end{array}
\right.\Rightarrow [A^{t},I]{\bf y}={\bf c},{\bf y}\geq 0\\
\end{array}
$$
where
$$
X=\left[
\begin{array}{c}
x_1\\
x_2\\
x_3\\
x_4\\
y_1\\
y_2\\
y_3\\
y_4\\
\end{array}
\right],
Q=
\left[\begin{array}{cccc}
 1 &  -2 &  -1 &  0 &  0 &  0 &  0 &  0 \\
 -1 &  -1 &  0 & -1 &  0 &  0 &  0 &  0 \\
 0 &  0 &  0 &  0 &  1 &  -1 &  1 &  0 \\
 0 &  0 &  0 &  0 &  -2 &  -1 &  0 &  1 \\
\end{array}\right]
$$

In [6]:
n=2
m=2
A=np.zeros((n,m))
A[0,0]=1
A[0,1]=-2
A[1,0]=-1
A[1,1]=-1
print(A)
I=np.identity(2)
print(I)
print(np.hstack((A,-I)))
print(np.hstack((A,-I,np.zeros((m,n+m)))))
print(np.hstack((np.zeros((m,n+m)),A.transpose(),-I)))
Q11=np.hstack((A,-I,np.zeros((m,n+m))))
Q21=np.hstack((np.zeros((m,n+m)),A.transpose(),-I))
Q=np.vstack((Q11,Q21))

[[ 1. -2.]
 [-1. -1.]]
[[1. 0.]
 [0. 1.]]
[[ 1. -2. -1. -0.]
 [-1. -1. -0. -1.]]
[[ 1. -2. -1. -0.  0.  0.  0.  0.]
 [-1. -1. -0. -1.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  1. -1. -1. -0.]
 [ 0.  0.  0.  0. -2. -1. -0. -1.]]


In [7]:
X=np.zeros((2*(m+n),1))
X[0,0]=4/3
X[1,0]=8/3
X[4,0]=2/3
X[5,0]=5/3
Q=np.array(Q)
print(Q.dot(X))

[[-4.]
 [-4.]
 [-1.]
 [-3.]]
