In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<img src="http://140.116.53.170/classes/numericalOptimization/InteriorPointMethods/figure000.png" with="600" heigh="400">

In [2]:
m,n=2,4
A=np.zeros((m,n))
A[0,0]=1
A[0,1]=-2
A[0,2]=-1
A[0,3]=0
A[1,0]=-1
A[1,1]=-1
A[1,2]=0
A[1,3]=-1
b=np.zeros((m,1))
b[0,0]=-4
b[1,0]=-4
c=np.zeros((n,1))
c[0,0]=-1
c[1,0]=-3
c[2,0]=0
c[3,0]=0

<img src="http://140.116.53.170/classes/numericalOptimization/InteriorPointMethods/figure001.png" with="600" heigh="400">

In [3]:
barx=np.zeros((n,1))
barx[0,0]=1
barx[1,0]=1
barx[2,0]=4
barx[3,0]=4
r1=b-A.dot(barx)
print(r1)
bary=np.zeros((m,1))
bary[0,0]=1
bary[1,0]=1
bars=np.zeros((n,1))
bars[0,0]=1
bars[1,0]=1
bars[2,0]=1
bars[3,0]=1
r2=c-A.transpose().dot(bary)-bars
print(r2)
e=np.ones((n,1))
mu=100
print(mu*e)
barX=np.zeros((n,n))
barX[0,0]=barx[0,0]
barX[1,1]=barx[1,0]
barX[2,2]=barx[2,0]
barX[3,3]=barx[3,0]
for i in range(n):
    barX[i,i]=barx[i,0]
print(barX)
barS=np.zeros((n,n))
for i in range(n):
    barS[i,i]=bars[i,0]
print(barS)
r3=mu*e-barX.dot(barS).dot(e)
print(r3)

[[1.]
 [2.]]
[[-2.]
 [-1.]
 [ 0.]
 [ 0.]]
[[100.]
 [100.]
 [100.]
 [100.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 4.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[99.]
 [99.]
 [96.]
 [96.]]


<img src="http://140.116.53.170/classes/numericalOptimization/InteriorPointMethods/figure008.png" with="600" heigh="400">

In [7]:
r=np.vstack((r1,r2,r3))
print(r)
print(np.linalg.norm(r))
barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
print(barA)
np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))
barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
print(barA)
np.hstack((barS,np.zeros((n,m)),barX))
barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))
print(barA)
np.linalg.inv(barA)#inverse(barA)
DeltaX=np.linalg.inv(barA).dot(r)
print(DeltaX)
Deltax=DeltaX[0:n,:]
print(Deltax)
Deltay=DeltaX[n:n+m,:]
print(Deltay)
Deltas=DeltaX[n+m:2*n+m,:]
print(Deltas)
alphax=0.01
alphay=0.01
newx=barx+alphax*Deltax
newy=bary+alphay*Deltay
news=bars+alphay*Deltas#note alphay

###################################

barx=newx
bary=newy
bars=news
r1=b-A.dot(barx)
r2=c-A.transpose().dot(bary)-bars


barX=np.zeros((n,n))
for i in range(n):
    barX[i,i]=barx[i,0]
barS=np.zeros((n,n))
for i in range(n):
    barS[i,i]=bars[i,0]
r3=mu*e-barX.dot(barS).dot(e)



r=np.vstack((r1,r2,r3))
barA=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
barA=np.vstack((barA,np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))))
barA=np.vstack((barA,np.hstack((barS,np.zeros((n,m)),barX))))
print(np.linalg.norm(r))

[[ 1.]
 [ 2.]
 [-2.]
 [-1.]
 [ 0.]
 [ 0.]
 [99.]
 [99.]
 [96.]
 [96.]]
195.0487118644981
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]]
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -2. -1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  1.]]
[[ 1. -2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -2. -1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  4.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  4.]]
[[ 70.47169811]
 [ 19.83018868]
 [ 29.81132075]
 [-92.30188679]
 [ 16.54716981]
 [ 47.0754717 ]
 [ 28.52830189]
 [ 79.16981132]
 [ 16.

The standard form of the given LP
$$
\begin{array}{rl}
\min & -x_1-3x_2\\
s.t. & x_1-2x_2 \geq -4\\
     & -x_1-x_2\geq -4\\
     &x_1,x_2\geq 0
\end{array}
$$
is 
$$
\begin{array}{rl}
\min & -x_1-3x_2\\
s.t. & x_1-2x_2-x_3 =-4\\
     & -x_1-x_2-x_4 =-4\\
     &x_1,x_2,x_3,x_4\geq 0
\end{array}.
$$