In [1]:
import numpy as np

<h1>Pseudocode of Bisection Method</h1>
<h4>Input</h4> <p>Input the endpoints $\alpha_a,\alpha_b$; tolerance $TOL$; maximum number of iterations $N_{0}$</p>
<h4>Step 0:</h4> <p>Set $i=1$.</p>
<h4>Step 1:</h4> <p>If $i\leq N_{0}$, then set $\alpha_p=\alpha_a+(\alpha_b-\alpha_a)/2$ and $FP=f(\alpha_p)$; go to <span style="font-weight:bold;font-size:1em;">Step 2</span>. Otherwise, STOP</p>
<h4>Step 2:</h4> <p>If $FP=0$ or $(\alpha_b-\alpha_a)/2<TOL$, then OUTPUT $(p)$ and STOP. Otherwise, set $i=i+1$ and go to <span style="font-weight:bold;font-size:1em;">Step 3</span>.</p></p>
<h4>Step 3:</h4> <p>If $FP<0$, then set $\alpha_a=\alpha_p$ and $FA=FP$. Otherwise, set $\alpha_b=\alpha_p$ and $FB=FP$. Go to <span style="font-weight:bold;font-size:1em;">Step 1</span>.</p>
<hr>

In [2]:
def feval(x):
    return x**2-2
sol=[]
a=1
b=2
print(a,b)
print(feval(a),feval(b))
c=(a+b)/2
if feval(c)<0:
    a=c
if feval(c)>0:
    b=c
if feval(c)==0:
    sol=c
print(a,b)
print(feval(a),feval(b))
c=(a+b)/2
if feval(c)<0:
    a=c
if feval(c)>0:
    b=c
if feval(c)==0:
    sol=c
print(a,b)
print(feval(a),feval(b))
c=(a+b)/2
if feval(c)<0:
    a=c
if feval(c)>0:
    b=c
if feval(c)==0:
    sol=c
print(a,b)
print(feval(a),feval(b))
c=(a+b)/2
if feval(c)<0:
    a=c
if feval(c)>0:
    b=c
if feval(c)==0:
    sol=c
print(a,b)
print(feval(a),feval(b))
c=(a+b)/2
if feval(c)<0:
    a=c
if feval(c)>0:
    b=c
if feval(c)==0:
    sol=c
print(a,b)
print(feval(a),feval(b))

1 2
-1 2
1 1.5
-1 0.25
1.25 1.5
-0.4375 0.25
1.375 1.5
-0.109375 0.25
1.375 1.4375
-0.109375 0.06640625
1.40625 1.4375
-0.0224609375 0.06640625


In [3]:
Nzero=20
def feval(x):
    return -x**2+2
sol=[]
a=1
b=2
Fa = feval(a)
Fb = feval(b)
print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
i=1
while i <=Nzero and np.abs(b-a)>1e-4 :
    print("%dth Step:"%i)
    c=(a+b)/2
    Fc=feval(c)
    if Fc*Fa>0:
        a=c
        Fa=Fc
    else :
        b=c
        Fb=Fc
    print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
    i=i+1
    


The function value of f(x)=-x^2+2 at x=1.000000 and x =2.000000 are 1.000000 and -2.000000
1th Step:
The function value of f(x)=-x^2+2 at x=1.000000 and x =1.500000 are 1.000000 and -0.250000
2th Step:
The function value of f(x)=-x^2+2 at x=1.250000 and x =1.500000 are 0.437500 and -0.250000
3th Step:
The function value of f(x)=-x^2+2 at x=1.375000 and x =1.500000 are 0.109375 and -0.250000
4th Step:
The function value of f(x)=-x^2+2 at x=1.375000 and x =1.437500 are 0.109375 and -0.066406
5th Step:
The function value of f(x)=-x^2+2 at x=1.406250 and x =1.437500 are 0.022461 and -0.066406
6th Step:
The function value of f(x)=-x^2+2 at x=1.406250 and x =1.421875 are 0.022461 and -0.021729
7th Step:
The function value of f(x)=-x^2+2 at x=1.414062 and x =1.421875 are 0.000427 and -0.021729
8th Step:
The function value of f(x)=-x^2+2 at x=1.414062 and x =1.417969 are 0.000427 and -0.010635
9th Step:
The function value of f(x)=-x^2+2 at x=1.414062 and x =1.416016 are 0.000427 and -0.005100


In [4]:
Nzero=20
def feval(x):
    return -x**2+2
sol=[]
a=1
b=2
Fa = feval(a)
Fb = feval(b)


print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
Fc=feval((a+b)/2)
i=1
while i <=Nzero and np.abs(b-a)>1e-4 and np.abs(Fc)>1e-4:
    print("%dth Step:"%i)
    c=(a+b)/2
    Fc=feval(c)
    if Fc*Fa>0:
        a=c
        Fa=Fc
    else :
        b=c
        Fb=Fc
    print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
    i=i+1

The function value of f(x)=-x^2+2 at x=1.000000 and x =2.000000 are 1.000000 and -2.000000
1th Step:
The function value of f(x)=-x^2+2 at x=1.000000 and x =1.500000 are 1.000000 and -0.250000
2th Step:
The function value of f(x)=-x^2+2 at x=1.250000 and x =1.500000 are 0.437500 and -0.250000
3th Step:
The function value of f(x)=-x^2+2 at x=1.375000 and x =1.500000 are 0.109375 and -0.250000
4th Step:
The function value of f(x)=-x^2+2 at x=1.375000 and x =1.437500 are 0.109375 and -0.066406
5th Step:
The function value of f(x)=-x^2+2 at x=1.406250 and x =1.437500 are 0.022461 and -0.066406
6th Step:
The function value of f(x)=-x^2+2 at x=1.406250 and x =1.421875 are 0.022461 and -0.021729
7th Step:
The function value of f(x)=-x^2+2 at x=1.414062 and x =1.421875 are 0.000427 and -0.021729
8th Step:
The function value of f(x)=-x^2+2 at x=1.414062 and x =1.417969 are 0.000427 and -0.010635
9th Step:
The function value of f(x)=-x^2+2 at x=1.414062 and x =1.416016 are 0.000427 and -0.005100


In [5]:
Nzero=20
def feval(x):
    return -x**2+2
sol=[]
a=1.9
b=2
Fa = feval(a)
Fb = feval(b)

if Fa*Fb<0:
    print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
    Fc=feval((a+b)/2)
    i=1
    while i <=Nzero and np.abs(b-a)>1e-4 and np.abs(Fc)>1e-4:
        print("%dth Step:"%i)
        c=(a+b)/2
        Fc=feval(c)
        if Fc*Fa>0:
            a=c
            Fa=Fc
        else :
            b=c
            Fb=Fc
        print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
        i=i+1
else:
    print("The function f(x)=-x^2+2 may does not have any zero on [%f,%f]"%(a,b))


The function f(x)=-x^2+2 may does not have any zero on [1.900000,2.000000]


# Solutions of Equations in One Variable: Newton Method



Finding a root, or solution, of an equation
of the form $f(x)=0$, for a given function $f$. A root of this equation is also called a <b>zero</b>
of the function $f$.


Suppose we want to solve:
$$
\begin{array}{rl}
\hbox{(P:)} & \displaystyle \min_{{\bf x} \in {\mathbb{R}}^{n}} \, f({\bf x}) \\
\end{array}
$$
At ${\bf x} = \bar{{\bf x}}$, $f({\bf x})$ can be approximated by:
$$f({\bf x}) \thickapprox h({\bf x}):= f(\bar{{\bf x}}) + \nabla f(\bar{{\bf x}})^{T}({\bf x}-\bar{{\bf x}}) + \displaystyle \frac{1}{2} ({\bf x} - \bar{{\bf x}})^{t} H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}}),$$
which is the quadratic Taylor expansion of $f({\bf x})$ at ${\bf x} = \bar{{\bf x}}$. Here $\nabla f({\bf x})$ is
the gradient of $f({\bf x})$ and $H({\bf x})$ is the Hessian of $f({\bf x})$.

Newton Direction


The function $h({\bf x}):= f(\bar{{\bf x}}) + \nabla f(\bar{{\bf x}})^{T}({\bf x}-\bar{{\bf x}}) + \displaystyle \frac{1}{2} ({\bf x} - \bar{{\bf x}})^{t} H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}})$ is a quadratic function, which is minimized by solving
$\nabla h({\bf x}) = 0$.
<ul>
    <li>Since the gradient of $h({\bf x})$ is:
        $$\nabla h({\bf x}) = {\nabla f(\bar{{\bf x}}) + H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}})},$$</li>
    <li>We therefore are motivated to solve:
$$ \nabla f(\bar{{\bf x}}) + H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}}) = 0,$$
which yields
$${\bf x} - \bar{{\bf x}} = {-H(\bar{{\bf x}})^{-1} \nabla f(\bar{{\bf x}})}$$
provided that \alertred{the inverse of $H(\bar{{\bf x}})$ exists}. </li>
    <li>The direction $-H(\bar{{\bf x}})^{-1} \nabla f(\bar{{\bf x}})$ is called the {\bf Newton direction}, or {\bf the Newton step} at ${\bf x} = \bar{{\bf x}}$. </li>
</ul>

<h1>Newton Method</h1>
<h4>Input</h4> <p>Input the initial approximation ${\bf x}^{1}$</p>
<h4>Step 0:</h4> <p>Given ${\bf x}^{1}$, set $k = 1$.</p>
<h4>Step 1:</h4> <p> Set ${\bf d}^{k} = -H({\bf x}^{k})^{-1} \nabla f({\bf x}^{k})$.</p>
<h4>Step 2:</h4> <p>If ${\bf d}^{k} = 0$, then stop. Otherwise, Choose step-size $\alpha^{k} = 1$.</p>
<h4>Step 3:</h4> <p>Set ${\bf x}^{k+1} = {\bf x}^{k} + \alpha^{k} {\bf d}^{k}$, and $k = k + 1$. Go to <span style="font-weight:bold;font-size:1em;">Step 1</span>.</p>
<hr>

In [6]:
Nzero=20
def feval(x):
    return -x**2+2
def geval(x):
    return -2*x
xk=1
print(xk)
print(feval(xk))
print(geval(xk))
xk=xk-feval(xk)/geval(xk)
print(xk)
print(feval(xk))
print(geval(xk))
xk=xk-feval(xk)/geval(xk)
print(xk)
print(feval(xk))
print(geval(xk))
xk=xk-feval(xk)/geval(xk)
print(xk)
print(feval(xk))
print(geval(xk))
xk=xk-feval(xk)/geval(xk)
print(xk)
print(feval(xk))
print(geval(xk))






sol=[]
a=1.9
b=2
Fa = feval(a)
Fb = feval(b)

if Fa*Fb<0:
    print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
    Fc=feval((a+b)/2)
    i=1
    while i <=Nzero and np.abs(b-a)>1e-4 and np.abs(Fc)>1e-4:
        print("%dth Step:"%i)
        c=(a+b)/2
        Fc=feval(c)
        if Fc*Fa>0:
            a=c
            Fa=Fc
        else :
            b=c
            Fb=Fc
        print("The function value of f(x)=-x^2+2 at x=%f and x =%f are %f and %f"%(a,b,Fa,Fb))
        i=i+1
else:
    print("The function f(x)=-x^2+2 may does not have any zero on [%f,%f]"%(a,b))


1
1
-2
1.5
-0.25
-3.0
1.4166666666666667
-0.006944444444444642
-2.8333333333333335
1.4142156862745099
-6.007304882871267e-06
-2.8284313725490198
1.4142135623746899
-4.510614104447086e-12
-2.8284271247493797
The function f(x)=-x^2+2 may does not have any zero on [1.900000,2.000000]


In [7]:
Nzero=20
def feval(x):
    return -x**2+2
def geval(x):
    return -2*x
xk=1

i=1
while i <=Nzero and np.abs(feval(xk))>1e-8:
    print("The function value of f(x)=-x^2+2 at x=%f is %f "%(xk,feval(xk)))
    print(xk)
    print(feval(xk))
    print(geval(xk))
    xk=xk-feval(xk)/geval(xk)
    i=i+1
print("The function value of f(x)=-x^2+2 at x=%.8f is %.8f "%(xk,feval(xk)))

The function value of f(x)=-x^2+2 at x=1.000000 is 1.000000 
1
1
-2
The function value of f(x)=-x^2+2 at x=1.500000 is -0.250000 
1.5
-0.25
-3.0
The function value of f(x)=-x^2+2 at x=1.416667 is -0.006944 
1.4166666666666667
-0.006944444444444642
-2.8333333333333335
The function value of f(x)=-x^2+2 at x=1.414216 is -0.000006 
1.4142156862745099
-6.007304882871267e-06
-2.8284313725490198
The function value of f(x)=-x^2+2 at x=1.41421356 is -0.00000000 


In [8]:
def feval(x):
    y=np.zeros((3,1))
    y[0,0]=x[0,0]+x[1,0]+x[2,0]
    y[1,0]=-x[0,0]**2+x[1,0]
    y[2,0]=np.cos(x[2,0])
    return y
x=np.zeros((3,1))
x[0,0]=2
x[1,0]=4
x[2,0]=8
feval(x)

array([[14.        ],
       [ 0.        ],
       [-0.14550003]])

In [9]:
def gfeval(x):
    y=np.zeros((3,3))
    y[0,0]=1
    y[0,1]=x[2,0]
    y[0,2]=x[1,0]
    y[1,0]=-2*x[0,0]
    y[1,1]=1
    y[1,2]=0
    y[2,0]=0
    y[2,1]=0
    y[2,2]=-np.sin(x[2,0])
    return y
gfeval(x)

array([[ 1.        ,  8.        ,  4.        ],
       [-4.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        , -0.98935825]])

In [10]:
np.linalg.inv(gfeval(x))

array([[ 0.03030303, -0.24242424,  0.12251591],
       [ 0.12121212,  0.03030303,  0.49006362],
       [-0.        , -0.        , -1.01075622]])

In [11]:
xk=np.zeros((3,1))
xk[0,0]=2
xk[1,0]=4
xk[2,0]=8
feval(x)
xk=xk-np.linalg.inv(gfeval(x)).dot(feval(xk))
print(xk)

[[1.59358364]
 [2.37433458]
 [7.85293494]]


In [12]:
np.abs(feval(xk))

array([[1.18208532e+01],
       [1.65174254e-01],
       [1.04669773e-03]])

In [13]:
print(np.sqrt(feval(xk)[0,0]**2+feval(xk)[1,0]**2+feval(xk)[2,0]**2))
np.linalg.norm(feval(xk))

11.822007146858938


11.822007146858938