In [1]:
import numpy as np

# Solutions of Equations in One Variable: Newton Method



Finding a root, or solution, of an equation
of the form $f(x)=0$, for a given function $f$. A root of this equation is also called a <b>zero</b>
of the function $f$.


Suppose we want to solve:
$$
\begin{array}{rl}
\hbox{(P:)} & \displaystyle \min_{{\bf x} \in {\mathbb{R}}^{n}} \, f({\bf x}) \\
\end{array}
$$
At ${\bf x} = \bar{{\bf x}}$, $f({\bf x})$ can be approximated by:
$$f({\bf x}) \thickapprox h({\bf x}):= f(\bar{{\bf x}}) + \nabla f(\bar{{\bf x}})^{T}({\bf x}-\bar{{\bf x}}) + \displaystyle \frac{1}{2} ({\bf x} - \bar{{\bf x}})^{t} H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}}),$$
which is the quadratic Taylor expansion of $f({\bf x})$ at ${\bf x} = \bar{{\bf x}}$. Here $\nabla f({\bf x})$ is
the gradient of $f({\bf x})$ and $H({\bf x})$ is the Hessian of $f({\bf x})$.

Newton Direction


The function $h({\bf x}):= f(\bar{{\bf x}}) + \nabla f(\bar{{\bf x}})^{T}({\bf x}-\bar{{\bf x}}) + \displaystyle \frac{1}{2} ({\bf x} - \bar{{\bf x}})^{t} H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}})$ is a quadratic function, which is minimized by solving
$\nabla h({\bf x}) = 0$.
<ul>
    <li>Since the gradient of $h({\bf x})$ is:
        $$\nabla h({\bf x}) = {\nabla f(\bar{{\bf x}}) + H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}})},$$</li>
    <li>We therefore are motivated to solve:
$$ \nabla f(\bar{{\bf x}}) + H(\bar{{\bf x}}) ({\bf x} - \bar{{\bf x}}) = 0,$$
which yields
$${\bf x} - \bar{{\bf x}} = {-H(\bar{{\bf x}})^{-1} \nabla f(\bar{{\bf x}})}$$
provided that \alertred{the inverse of $H(\bar{{\bf x}})$ exists}. </li>
    <li>The direction $-H(\bar{{\bf x}})^{-1} \nabla f(\bar{{\bf x}})$ is called the {\bf Newton direction}, or {\bf the Newton step} at ${\bf x} = \bar{{\bf x}}$. </li>
</ul>

<h1>Newton Method</h1>
<h4>Input</h4> <p>Input the initial approximation ${\bf x}^{1}$</p>
<h4>Step 0:</h4> <p>Given ${\bf x}^{1}$, set $k = 1$.</p>
<h4>Step 1:</h4> <p> Set ${\bf d}^{k} = -H({\bf x}^{k})^{-1} \nabla f({\bf x}^{k})$.</p>
<h4>Step 2:</h4> <p>If ${\bf d}^{k} = 0$, then stop. Otherwise, Choose step-size $\alpha^{k} = 1$.</p>
<h4>Step 3:</h4> <p>Set ${\bf x}^{k+1} = {\bf x}^{k} + \alpha^{k} {\bf d}^{k}$, and $k = k + 1$. Go to <span style="font-weight:bold;font-size:1em;">Step 1</span>.</p>
<hr>

In [2]:
Nzero=20
def feval(x):
    return -x**2+2

def gfeval(x):
    return -2*x
xk=1

i=1
while i<=Nzero and np.abs(feval(xk))>1e-8:
    print("The function value of f(x)=-x^2+2 at x=%.8f is %.8f." % (xk,feval(xk)))
    print(xk)
    print(feval(xk))
    print(gfeval(xk))
    xk=xk-feval(xk)/gfeval(xk)
    i=i+1
print("The function value of f(x)=-x^2+2 at x=%.8f is %.8f." % (xk,feval(xk)))

The function value of f(x)=-x^2+2 at x=1.00000000 is 1.00000000.
1
1
-2
The function value of f(x)=-x^2+2 at x=1.50000000 is -0.25000000.
1.5
-0.25
-3.0
The function value of f(x)=-x^2+2 at x=1.41666667 is -0.00694444.
1.4166666666666667
-0.006944444444444642
-2.8333333333333335
The function value of f(x)=-x^2+2 at x=1.41421569 is -0.00000601.
1.4142156862745099
-6.007304882871267e-06
-2.8284313725490198
The function value of f(x)=-x^2+2 at x=1.41421356 is -0.00000000.


In [3]:
Nzero=20
def feval(x):
    return 2*x**3-3*x**2+5*x-7

def gfeval(x):
    return 6*x**2-6*x+5

def NewtonMethod(xk,Nzero,epsilon=1e-8):
    i=1
    while i<=Nzero and np.abs(feval(xk))>epsilon:
        #print("The function value of f(x)=2x^3-3x^2+5x-7 at x=%.8f is %.8f." % (xk,feval(xk)))
        #print(xk)
        #print(feval(xk))
        #print(gfeval(xk))
        xk=xk-feval(xk)/gfeval(xk)
        i=i+1
    print("The function value of f(x)=f(x)=2x^3-3x^2+5x-7at x=%.8f is %.8f." % (xk,feval(xk)))
    return(xk,feval(xk))
x=[]
y=[]

for i in range(20):
    x.append(-10+i*1)
    y.append(feval(x[i]))
    xk=-3
    print(x,y)
xk=[]
zeros=[]
fvalue=[]
for i in range(19):
    if y[i]*y[i+1]<0:
        zk,yk=NewtonMethod(x[i],Nzero)
        xk.append(x[i])
        zeros.append(zk)
        fvalue.append(yk)
print(xk)
print(zeros)
print(fvalue)

[-10] [-2357]
[-10, -9] [-2357, -1753]
[-10, -9, -8] [-2357, -1753, -1263]
[-10, -9, -8, -7] [-2357, -1753, -1263, -875]
[-10, -9, -8, -7, -6] [-2357, -1753, -1263, -875, -577]
[-10, -9, -8, -7, -6, -5] [-2357, -1753, -1263, -875, -577, -357]
[-10, -9, -8, -7, -6, -5, -4] [-2357, -1753, -1263, -875, -577, -357, -203]
[-10, -9, -8, -7, -6, -5, -4, -3] [-2357, -1753, -1263, -875, -577, -357, -203, -103]
[-10, -9, -8, -7, -6, -5, -4, -3, -2] [-2357, -1753, -1263, -875, -577, -357, -203, -103, -45]
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1] [-2357, -1753, -1263, -875, -577, -357, -203, -103, -45, -17]
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0] [-2357, -1753, -1263, -875, -577, -357, -203, -103, -45, -17, -7]
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1] [-2357, -1753, -1263, -875, -577, -357, -203, -103, -45, -17, -7, -3]
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2] [-2357, -1753, -1263, -875, -577, -357, -203, -103, -45, -17, -7, -3, 7]
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0

In [8]:
Nzero=20
def feval(x):
    y=np.zeros((2,1))
    y[0,0]=np.exp(x[0,0])+x[1,0]-4
    y[1,0]=x[0,0]+x[1,0]-1
    return y

def gfeval(x):
    y=np.zeros((2,2))
    y[0,0]=np.exp(x[0,0])
    y[1,0]=1
    y[0,1]=1
    y[1,1]=1
    return y
    

def NewtonMethod(xk,Nzero,epsilon=1e-8):
    i=1
    #while i<=Nzero and np.abs(feval(xk))>epsilon:
    while i<=Nzero and np.linalg.norm(feval(xk))>epsilon:
        #print("The function value of f(x)=2x^3-3x^2+5x-7 at x=%.8f is %.8f." % (xk,feval(xk)))
        #print(xk)
        #print(feval(xk))
        #print(gfeval(xk))
        xk=xk-np.linalg.inv(gfeval(xk)).dot(feval(xk))
        i=i+1
    print("The function value of f(x)=f(x)=2x^3-3x^2+5x-7at x=(%.8f,%.8f) is (%.8f,%.8f)." % (xk[0,0],xk[1,0],feval(xk)[0,0],feval(xk)[1,0]))
    return xk,feval(xk)

    
x=np.array([[1],[1]])#2*1
print(feval(x))
print(gfeval(x))
#x=np.array([1,1])#1*2
#feval(x)
NewtonMethod(x,Nzero)

[[-0.28171817]
 [ 1.        ]]
[[2.71828183 1.        ]
 [1.         1.        ]]
The function value of f(x)=f(x)=2x^3-3x^2+5x-7at x=(1.50524150,-0.50524150) is (0.00000000,0.00000000).


(array([[ 1.5052415],
        [-0.5052415]]),
 array([[1.79412041e-13],
        [0.00000000e+00]]))

In [18]:
from scipy.optimize import fsolve
import numpy as np

# Define the system of equations
def equations(vars):
    x, y = vars
    eq1 = np.exp(x) + y - 4
    eq2 = x + y - 1
    return [eq1, eq2]

# Initial guess for the solution
initial_guess = [0, 0]

# Use fsolve to find the roots
roots = fsolve(equations, initial_guess)

print("Approximate Zeros:")
print("x =", roots[0])
print("y =", roots[1])

Approximate Zeros:
x = 0.00017944262673371664
y = 0.00018676831076708218


/Users/jameslin/anaconda3/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py:178: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
