In [2]:
import numpy as np

<ol>
    <li>Ace Novelty Company has determined that the profit for each Type A, Type B, and Type C souvenir that it plans to produce is 6 dollars, 5 dollars, and 4 dollars, respectively.</li>

<li>To manufacture a Type A souvenir requires 2 minutes on Machine I, 1 minute on Machine II, and 2 minutes on Machine III. A Type B souvenir requires 1 minute on Machine I, 3 minutes on Machine II, and 1 minute on Machine III.</li>

<li>A Type C souvenir requires 1 minute on Machine I and 2 minutes on each of Machines II and III.</li>

<li>Each day, there are 3 hours available on Machine I, 5 hours available on Machine II, and 4 hours available on Machine III for manufacturing these souvenirs.</li>

<li>How many souvenirs of each type should Ace Novelty make per day to maximize its profit?</li>
</ol>

The given information is tabulated as follows:

<img src="http://140.116.53.170/classes/numericalOptimization/simplexMethods/ch4-p64.png" width="600" alt="Given Information">


Solution:

<ol>
    <li>Let $x$, $y$, and $z$ denote the respective numbers of Type A, Type B, and Type C souvenirs to be made.</li>
    <li>The total amount of time that Machine I is used is given by $2x + y + z$ minutes and must not exceed 180 minutes.</li>
    <li>Thus, we have the inequality
    $$
    2x+y+z \leq 180
    $$</li>
    <li>Similar considerations on the use of Machines II and III lead to the inequalities
    $$
    x+3y+2z \leq 300
    $$
    $$
    2x+y+2z \leq 240
    $$</li>

<li>The profit resulting from the sale of the souvenirs produced is given by
    $$
    P = 6x + 5y + 4z
    $$</li>
<li>The mathematical formulation of this problem leads to the following standard linear programming problem: Maximize the objective (profit) function $P = 6x + 5y + 4z$  subject to
    $$
    2x + y + z \leq 180
    $$
    $$
    x + 3y + 2z \leq 300
    $$
    $$
    2x + y + 2z \leq 240
    $$
    $$
    x \geq 0 ,y \geq 0 ,z \geq 0
    $$</li>

<li>Introducing the slack variables u, v, and w gives the system of linear equations
    $$
    P-6x-5y-4z= 0
    $$
    $$
    2x + y + z + u = 180
    $$
    $$
    x + 3y + 2z + v = 300
    $$
    $$
    2x + y + 2z + w = 240
    $$
    </li>
</ol>

# Simplex Tableau
# Step 0:

$$
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & -6 & -5 & -4 & 0 & 0 & 0 &  0 \\
    \hline
    0  & 2   & 1   & 1   & 1 & 0 & 0 &  180 \\
    0  & 1   & 3   & 2   & 0 & 1 & 0 &  300 \\
    0  & 2   & 1   & 2   & 0 & 0 & 1 &  240 \\
\end{array}
$$

# Step 1:

$$
{\frac{1}{2}R_{1}\atop \longrightarrow}
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & -6 & -5 & -4 & 0 & 0 & 0 &  0 \\
    \hline
    0  & 1   & 1/2   & 1/2   & 1/2 & 0 & 0 &  90 \\
    0  & 1   & 3   & 2   & 0 & 1 & 0 &  300 \\
    0  & 2   & 1
    & 2   & 0 & 0 & 1 &  240 \\
\end{array}
$$

# Step 2:

$$
{R_{0}+6R_{1}\atop \longrightarrow}
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & 0 & -2 & -1 & 3 & 0 & 0 &  540 \\
    \hline
    0  & 1   & 1/2   & 1/2   & 1/2 & 0 & 0 &  90 \\
    0  & 1   & 3   & 2   & 0 & 1 & 0 &  300 \\
    0  & 2   & 1   & 2   & 0 & 0 & 1 &  240 \\
\end{array}
$$

# Step 3:

$$
{R_{2}-R_{1}\atop \longrightarrow}
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & 0 & -2 & -1 & 3 & 0 & 0 &  540 \\
    \hline
    0  & 1   & 1/2   & 1/2   & 1/2 & 0 & 0 &  90 \\
    0  & 0   & 5/2   & 3/2   & -1/2 & 1 & 0 &  210 \\
    0  & 2   & 1     & 2   & 0 & 0 & 1 &  240 \\
\end{array}
$$

# Step 4:

$$
{R_{3}-2R_{1}\atop \longrightarrow}
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & 0 & -2 & -1 & 3 & 0 & 0 &  540 \\
    \hline
    0  & 1   & 1/2   & 1/2   & 1/2 & 0 & 0 &  90 \\
    0  & 0   & 5/2   & 3/2   & -1/2 & 1 & 0 &  210 \\
    0  & 0   & -1   & 1   & -1 & 0 & 1 &  60 \\
\end{array}
$$

# Step 5:

$$
{\frac{2}{5}R_{2}\atop \longrightarrow}
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & 0 & -2 & -1 & 3 & 0 & 0 &  540 \\
    \hline
    0  & 1   & 1/2   & 1/2   & 1/2 & 0 & 0 &  90 \\
    0  & 0   & 1   & 3/5   & -1/5 & 2/5 & 0 &  84 \\
    0  & 0   & 0   & 1   & -1 & 0 & 1 &  60 \\
\end{array}
$$

# Step 6:

$$
{R_{1}-\frac{1}{2}R_{2}\atop \longrightarrow}
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & 0 & 0 & 1/5 & 13/5 & 4/5 & 0 &  708 \\
    \hline
    0  & 1   & 0   & 1/5   & 3/5 & -1/5 & 0 &  48 \\
    0  & 0   & 1   & 3/5   & -1/5 & 2/5 & 0 &  84 \\
    0  & 0   & 0   & 1   & -1 & 0 & 1 &  60 \\
\end{array}
$$

Let us go back to the initial step.
$$
\begin{array}{rrrrrrr|c}
    P  & x   & y   & z   & u & v & w & RHS\\
    \hline
    1  & -6 & -5 & -4 & 0 & 0 & 0 &  0 \\
    \hline
    0  & 2   & 1   & 1   & 1 & 0 & 0 &  180 \\
    0  & 1   & 3   & 2   & 0 & 1 & 0 &  300 \\
    0  & 2   & 1   & 2   & 0 & 0 & 1 &  240 \\
\end{array}
$$
We store the initial tableau in a matrix $A$. Only values are stored in $A$.

In [3]:
A=np.zeros((4,8))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
A[0,0]=1
A[0,1]=-6
A[0,2]=-5
A[0,3]=-4
A[1,1]=2
A[1,2]=1
A[1,3]=1
A[1,4]=1
A[1,7]=180
A[2,1]=1
A[2,2]=3
A[2,3]=2
A[2,4]=0
A[2,5]=1
A[2,7]=300
A[3,1]=2
A[3,2]=1
A[3,3]=2
A[3,6]=1
A[3,7]=240

In [7]:
print(A)

[[  1.  -6.  -5.  -4.   0.   0.   0.   0.]
 [  0.   2.   1.   1.   1.   0.   0. 180.]
 [  0.   1.   3.   2.   0.   1.   0. 300.]
 [  0.   2.   1.   2.   0.   0.   1. 240.]]


To perform any of the three row operations on a matrix $A$, it suffices to take the product  $E_1A$, 
where $E_1$ is the elementary matrix obtained by using the desired row operation on the identity matrix.

# Multiplication by a Scalar and Elementary Matrices

Let $E^1_{i,k}$ denote the elementary matrix corresponding to the row operation in which the $i^{th}$ 
row is multiplied by the nonzero scalar, $k$. Then
$$E^1_{i,k}A=B$$ 
where $B$ is obtained from $A$ by multiplying the $i^{th}$ row of $A$ by $k$.

We define this elementary matrix as follows:

In [8]:
import numpy as np
def E1(A,i,k):
    m=len(A)
    n=len(A[0,:])
    I=np.identity(m)
    I[i,i]=k
    return I.dot(A)

# Adding Multiples of Rows and Elementary Matrices
Let  $E^2_{i,j,k}$ denote the elementary matrix obtained from $I$ by adding $k$
times the $i^{th}$ row to the $j^{th}$. Then
$$
E^{2}_{i,j,k} A=B
$$ 
where $B$ is obtained from $A$ by adding $k$ times the $i^{th}$ row to the $j^{th}$ row of $A$.

In [11]:
def E2(A,i,j,k):
    m=len(A)
    n=len(A[0,:])
    I=np.identity(m)
    I[j,i]=k
    return I.dot(A)

Now we want to produce the matrix in Step 1:

In [10]:
print(A)
A=E1(A,1,1/2)
print(A)

[[  1.  -6.  -5.  -4.   0.   0.   0.   0.]
 [  0.   2.   1.   1.   1.   0.   0. 180.]
 [  0.   1.   3.   2.   0.   1.   0. 300.]
 [  0.   2.   1.   2.   0.   0.   1. 240.]]
[[  1.   -6.   -5.   -4.    0.    0.    0.    0. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    1.    3.    2.    0.    1.    0.  300. ]
 [  0.    2.    1.    2.    0.    0.    1.  240. ]]


Also, we can produce the matrix in Step 2:

In [15]:
A= E2(A,1,0,6)
print(A)

[[  1.    0.   -2.   -1.    3.    0.    0.  540. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    1.    3.    2.    0.    1.    0.  300. ]
 [  0.    2.    1.    2.    0.    0.    1.  240. ]]


In [16]:
np.set_printoptions(precision=3,suppress=True)
print(A)

[[  1.    0.   -2.   -1.    3.    0.    0.  540. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    1.    3.    2.    0.    1.    0.  300. ]
 [  0.    2.    1.    2.    0.    0.    1.  240. ]]


In [18]:
A = E2(A,1,2,-1)
print(A)

[[  1.    0.   -2.   -1.    3.    0.    0.  540. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    0.    2.5   1.5  -0.5   1.    0.  210. ]
 [  0.    2.    1.    2.    0.    0.    1.  240. ]]


In [19]:
A = E2(A,1,3,-2)
print(A)

[[  1.    0.   -2.   -1.    3.    0.    0.  540. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    0.    2.5   1.5  -0.5   1.    0.  210. ]
 [  0.    0.    0.    1.   -1.    0.    1.   60. ]]


Then we obtain the matrix in Step 4:

In [26]:
A=np.zeros((4,8))
A[0,0]=1
A[0,1]=-6
A[0,2]=-5
A[0,3]=-4
A[1,1]=2
A[1,2]=1
A[1,3]=1
A[1,4]=1
A[1,7]=180
A[2,1]=1
A[2,2]=3
A[2,3]=2
A[2,4]=0
A[2,5]=1
A[2,7]=300
A[3,1]=2
A[3,2]=1
A[3,3]=2
A[3,6]=1
A[3,7]=240
print(A)
###
p = 1
#####
A=E1(A,p,1/A[p,p])#A= E2(A,p,0.6)
#####
l= 0
#####
A=E2(A,p,l,-A[l,p])#A= E2(A,p,0.6)
######
l=2
######
A=E2(A,p,l,-A[l,p])#A= E2(A,2,-1)
######
l=3
####
A=E2(A,p,l,-A[l,p])#A= E2(A,3,-2)
print(A)

[[  1.  -6.  -5.  -4.   0.   0.   0.   0.]
 [  0.   2.   1.   1.   1.   0.   0. 180.]
 [  0.   1.   3.   2.   0.   1.   0. 300.]
 [  0.   2.   1.   2.   0.   0.   1. 240.]]
[[  1.    0.   -2.   -1.    3.    0.    0.  540. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    0.    2.5   1.5  -0.5   1.    0.  210. ]
 [  0.    0.    0.    1.   -1.    0.    1.   60. ]]


In [28]:
A=np.zeros((4,8))
A[0,0]=1
A[0,1]=-6
A[0,2]=-5
A[0,3]=-4
A[1,1]=2
A[1,2]=1
A[1,3]=1
A[1,4]=1
A[1,7]=180
A[2,1]=1
A[2,2]=3
A[2,3]=2
A[2,4]=0
A[2,5]=1
A[2,7]=300
A[3,1]=2
A[3,2]=1
A[3,3]=2
A[3,6]=1
A[3,7]=240
print(A)
###
p = 1
#####
A=E1(A,p,1/A[p,p])#A= E2(A,p,0.6)
#####
for l in range(0,p):
    A=E2(A,p,l,-A[l,p])
    print(l)
print("")
for i in range(p+1,4):
    A=E2(A,p,l,-A[l,p])
    print(l)
#####
l= 0
#####
A=E2(A,p,l,-A[l,p])#A= E2(A,p,0.6)
######
l=2
######
A=E2(A,p,l,-A[l,p])#A= E2(A,2,-1)
######
l=3
####
A=E2(A,p,l,-A[l,p])#A= E2(A,3,-2)
print(A)

[[  1.  -6.  -5.  -4.   0.   0.   0.   0.]
 [  0.   2.   1.   1.   1.   0.   0. 180.]
 [  0.   1.   3.   2.   0.   1.   0. 300.]
 [  0.   2.   1.   2.   0.   0.   1. 240.]]
0

0
0
[[  1.    0.   -2.   -1.    3.    0.    0.  540. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    0.    2.5   1.5  -0.5   1.    0.  210. ]
 [  0.    0.    0.    1.   -1.    0.    1.   60. ]]


In [31]:
A=np.zeros((4,8))
A[0,0]=1
A[0,1]=-6
A[0,2]=-5
A[0,3]=-4
A[1,1]=2
A[1,2]=1
A[1,3]=1
A[1,4]=1
A[1,7]=180
A[2,1]=1
A[2,2]=3
A[2,3]=2
A[2,4]=0
A[2,5]=1
A[2,7]=300
A[3,1]=2
A[3,2]=1
A[3,3]=2
A[3,6]=1
A[3,7]=240
print(A)
###
p = 1
A=E1(A,p,1/A[p,p])
print(A)
for l in range(0,p):
    A=E2(A,p,l,-A[l,p])
    print(l)
print("")
for l in range(p+1,4):
    A=E2(A,p,l,-A[l,p])
    print(l)
print(A)
#################
p = 2
A=E1(A,p,1/A[p,p])#A= E2(A,p,0.6)
for l in range(0,p):
    A=E2(A,p,l,-A[l,p])
    print(l)
print("")
for l in range(p+1,4):
    A=E2(A,p,l,-A[l,p])
    print(l)
print(A)

[[  1.  -6.  -5.  -4.   0.   0.   0.   0.]
 [  0.   2.   1.   1.   1.   0.   0. 180.]
 [  0.   1.   3.   2.   0.   1.   0. 300.]
 [  0.   2.   1.   2.   0.   0.   1. 240.]]
[[  1.   -6.   -5.   -4.    0.    0.    0.    0. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    1.    3.    2.    0.    1.    0.  300. ]
 [  0.    2.    1.    2.    0.    0.    1.  240. ]]
0

2
3
[[  1.    0.   -2.   -1.    3.    0.    0.  540. ]
 [  0.    1.    0.5   0.5   0.5   0.    0.   90. ]
 [  0.    0.    2.5   1.5  -0.5   1.    0.  210. ]
 [  0.    0.    0.    1.   -1.    0.    1.   60. ]]
0
1

3
[[  1.    0.    0.    0.2   2.6   0.8   0.  708. ]
 [  0.    1.    0.    0.2   0.6  -0.2   0.   48. ]
 [  0.    0.    1.    0.6  -0.2   0.4   0.   84. ]
 [  0.    0.    0.    1.   -1.    0.    1.   60. ]]


In [ ]:
A=E2(A,1,)
A=E2(A,1)
A=E2(A,1)
print(A)

In [ ]:
A=np.zeros((4,8))


i=1
j=1
A=E1(A,i,1/A[i,j])
print(A)
l=2
print(A[i,j])
print(A[l,j])
A=E2(A,i,l,-A[i,j]/A[l,j])
print(A)

In [ ]:
A=np.zeros((4,8))


m=len(A)
n=len(A[0,:])

i=1
j=1
A=E1(A,i,1/A[i,j])
print(A)
for l in range(0,i):
    print(l)
    A=E2(A)
    print(A)
for l in range(i+1,m):
    print(l)
    A=E2(A)
    print(A)
print(A)


In [1]:
A=np.zeros((4,8))
A[0,0]=1
A[0,1]=-6
A[0,2]=-5
A[0,3]=-4
A[1,1]=2
A[1,2]=1
A[1,3]=1
A[1,4]=1
A[1,7]=180
A[2,1]=1
A[2,2]=3
A[2,3]=2
A[2,5]=1
A[2,7]=300
A[3,1]=2
A[3,3]=2
A[3,6]=1
A[3,7]=240

m=len(A)
n=len(A[0,:])

i=1
j=1
A=E1(A,i,1/A[i,j])
print(A)
for l in range(0,i):
    print(l)
    A=E2(A,i,l,-A[l,j])
    print(A)
for l in range(i+1,m):
    print(l)
    A=E2(A,i,l,-A[l,j])
    print(A)
print(A)



NameError: name 'np' is not defined

In [5]:
f = open("SimplexTabuleau.html", "w")
f.write("Now the file has more content!")
"""

f.write("<html lang="en">")
f.write("<head>")
f.write("<title>Simplex Tableau</title>")
f.write("<meta charset="utf-8">")
f.write("<meta name="viewport" content="width=device-width, initial-scale=1">")
f.write("<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">")
f.write("  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>")
f.write("  <script type="text/x-mathjax-config">")
f.write("  MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});")
f.write("</script>")
f.write("<script type="text/javascript"")
f.write("  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">")
f.write("</script>")
f.write("</head>")
f.write("<body>")
"""

f.write("<div class="container mt-3">")
f.write("<h2>Simplex Tableau</h2>")
f.write("<p>Setp 0:</p>")
f.write("<table class="table table-bordered table-hover "><tbody><tr>")
f.write("<th></th><th style="text-align:center">Z </th><th style="text-align:center">$x_1$ </th><th style="text-align:center">$x_2$ </th><th style="text-align:center">$x_3$ </th><th style="text-align:center">$x_4$ </th><th style="text-align:center">$x_5$ </th><th style="text-align:center">RHS </th><th style="text-align:center"> </th></tr> ")
f.write("<tr><td style="text-align:center">Z </td><td style="text-align:center"> 1.00  </td><td style="text-align:center"> -3.00  </td><td style="text-align:center"> -5.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> </td></tr> ")
f.write("<tr><td style="text-align:center">$x_3$ </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 1.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 1.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 4.00  </td><td style="text-align:center">-- </td></tr> ")
f.write("<tr><td style="text-align:center">$x_4$ </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 2.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 1.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 12.00  </td><td style="text-align:center"> 6.00  </td></tr> ")
f.write("<tr><td style="text-align:center">$x_5$ </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 3.00  </td><td style="text-align:center"> 2.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 0.00  </td><td style="text-align:center"> 1.00  </td><td style="text-align:center"> 18.00  </td><td style="text-align:center"> 9.00  </td></tr> ")
f.write("</tbody></table>")
f.write("</html>")
f.close()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2522996378.py, line 22)