In [1]:
import numpy as np
import random
import pandas as pd

# Example 1

Consider the function $f({\bf x}) = 5x_{0}^{2} + x_{1}^{2} + 4x_{0}x_{1} - 14x_{0} - 6x_{1} +20$.

Define
$$
{\bf x}=
\left[\begin{array}{cc}
x_{0}\\
x_{1}
\end{array}\right],
Q=
\left[\begin{array}{cc}
10&4\\
4&2
\end{array}\right]
\hbox{ and }
{\bf q}=
\left[\begin{array}{cc}
-14\\
-6
\end{array}\right].
$$

Then $f({\bf x})=\displaystyle \frac{1}{2}{\bf x}^tQ{\bf x}+{\bf q}^t {\bf x}+20$. 
<hr>

From the definition of gradients, we consider
$$f({\bf x}) = f({\bf\bar{x}}) + \nabla f({\bf\bar{x}})^{t}({\bf x}-{\bf\bar{x}}) + \| {\bf x}-{\bf\bar{x}} \| \alpha ({\bf\bar{x}},{\bf x}-{\bf\bar{x}}),$$
The computation is given as follows:
$$f({\bf x}) - f({\bf\bar{x}}) = \frac{1}{2}{\bf x}^tQ{\bf x}+{\bf q}^t{\bf x} - \left(\frac{1}{2}{\bf\bar{x}}^tQ{\bf\bar{x}}+{\bf q}^t{\bf\bar{x}}\right)$$
$$
= \frac{1}{2}{\bf x}^tQ{\bf x}+{\bf q}^t({\bf x}-{\bf\bar{x}}) -{\bf\bar{x}}^tQ{\bf\bar{x}} +\frac{1}{2}{\bf\bar{x}}^tQ{\bf\bar{x}}+ {\bf\bar{x}}^tQ{\bf x}-{\bf\bar{x}}^tQ{\bf x}
$$
$$
= {\bf\bar{x}}^t Q({\bf x}-{\bf\bar{x}}) +{\bf q}^t({\bf x}-{\bf\bar{x}})+\frac{1}{2}{\bf x}^tQ{\bf x}  +\frac{1}{2}{\bf\bar{x}}^tQ{\bf\bar{x}}-{\bf\bar{x}}^tQ{\bf x}
$$
$$
= (Q{\bf\bar{x}})^t({\bf x}-{\bf\bar{x}}) +{\bf q}^t({\bf x}-{\bf\bar{x}})+\frac{1}{2}{\bf x}^tQ({\bf x}-{\bf\bar{x}})  -\frac{1}{2}{\bf\bar{x}}^tQ({\bf x} -{\bf\bar{x}})
$$
$$
= (Q{\bf\bar{x}}+{\bf q})^t({\bf x}-{\bf\bar{x}}) +\frac{1}{2}({\bf x}-{\bf\bar{x}})^tQ({\bf x}-{\bf\bar{x}})
$$

Since
$$
\frac{\partial f}{\partial x_0}=10x_0+4x_1-14
$$
and 
$$
\frac{\partial f}{\partial x_1}=2x_1+4x_0-6,
$$
we obtain the graident $\nabla f(x)$ of $f(x)$ is 
$$
\nabla f(x_0,x_1)=\left[\begin{array}{c} 10x_0+4x_1-14 \\ 2x_1+4x_0-6 \end{array}\right].
$$
Moreover, 
$$
\nabla f(x_0,x_1)=Q\left[\begin{array}{c}x_0 \\ x_1 \end{array}\right]+q
$$
where 
$$
Q=\left[\begin{array}{cc}10 &４\\4 & 2\end{array}\right], 
q=\left[\begin{array}{cc}-14\\-6\end{array}\right].
$$
At the same time, the function $f(x_0,x_1) = 5x_{0}^{2} + x_{1}^{2} + 4x_{0}x_{1} - 14x_{0} - 6x_{1} +20$ can be rewritten as 
$$
f(x_0,x_1)=\frac{1}{2}\left[\begin{array}{cc}x_0 & x_1 \end{array}\right]
Q\left[\begin{array}{c}x_0 \\ x_1 \end{array}\right]+q^t\left[\begin{array}{c}x_0 \\ x_1 \end{array}\right]
$$
i.e.
$$
f({\bf x})=\frac{1}{2}{\bf x}^t Q{\bf x}+q^t{\bf x}\quad and\quad \nabla f({\bf x})=Q{\bf x}+q 
$$
where ${\bf x}=\left[\begin{array}{c}x_0 \\ x_1 \end{array}\right]$.
<hr>

In [2]:
Q=np.zeros((2,2))
Q[0,0]=10
Q[0,1]=4
Q[1,0]=4
Q[1,1]=2
print(Q)

[[10.  4.]
 [ 4.  2.]]


In [3]:
q=np.zeros((2,1))
q[0,0]=-14
q[1,0]=-6
print(q)

[[-14.]
 [ -6.]]


In [4]:
def functionValue(x,Q,q,f0):
    y=(1/2)*x.transpose().dot(Q).dot(x)+q.transpose().dot(x)+f0
    return y

def functionGradient(x,Q,q):
    d=Q.dot(x)+q
    return d

In [7]:
Q=np.array([[10,4],[4,2]])
q=np.array([[-14],[-6]])
f0=20
xk=[np.array([[0],[10]])]
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
#xk=[np.array([[100000],[100000]])]
k=0
dk=[]
alphak=[]
print(-functionGradient(xk[k],Q,q))

[[-26]
 [-14]]


A natural consequence of this is the following algorithm, called the steepest
descent algorithm.
    
Step 0: Given ${\bf x}^{0}$, set $k:=0$

Step 1: ${\bf d}^{k}:= -\nabla f({\bf x}^{k})$. If ${\bf d}^{k}=0$, then stop.

Step 2: Solve $\displaystyle \min_{\alpha >0} f({\bf x}^{k} + \alpha {\bf d}^{k})$ for the step size $\alpha^{k}$, perhaps chosen by an exact or inexact line search.

Step 3: Set ${\bf x}^{k+1} \leftarrow {\bf x}^{k} + \alpha^{k} {\bf d}^{k}$, $k \leftarrow k+1$.Go to Step 1.

Note from Step 2 and the fact that ${\bf d}^{k} = - \nabla f({\bf x}^{k})$
is a descent direction, it follows that $f({\bf x}^{k+1}) < f({\bf x}^{k}).$
<hr>

In [5]:
def determineStepSize(x,d):
    alpha=-(10*x[0]*d[0] + 2*x[1]*d[1] + 4*x[1]*d[0] + 4*x[0]*d[1]-14*d[0]-6*d[1])/(2*(5*d[0]**2 + d[1]**2 + 4*d[0]*d[1]))
    return alpha

In [6]:
def determineStepSize(x,Q,q,d):
    alpha=-(Q[0,0]*x[0]*d[0] + Q[1,1]*x[1]*d[1] + Q[0,1]*x[1]*d[0] + Q[1,0]*x[0]*d[1]+q[0,0]*d[0]+q[1,0]*d[1])
    alpha=alpha/(Q[0,0]*d[0]**2 + Q[1,1]*d[1]**2 + (Q[1,0]+Q[0,1])*d[0]*d[1])
    return alpha

In [7]:
Q=np.array([[10,4],[4,2]])
q=np.array([[-14],[-6]])
f0=20
xk=[np.array([[0],[10]])]
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
#xk=[np.array([[100000],[100000]])]
k=0
dk=[]
alphak=[]
#dk.append
dk.append(-functionGradient(xk[k],Q,q))
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    print("%d Step:" % k)
    #alphak.append
    alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    print(dk[k])
    xk.append(xk[k]+alphak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

0 Step:
[[-26]
 [-14]]
1 Step:
[[ 1.3799682 ]
 [-2.56279809]]
2 Step:
[[-6.35573927]
 [-3.42232114]]
3 Step:
[[ 0.33733531]
 [-0.62647986]]
4 Step:
[[-1.55367006]
 [-0.83659157]]
5 Step:
[[ 0.08246213]
 [-0.15314395]]
6 Step:
[[-0.37979699]
 [-0.20450607]]
7 Step:
[[ 0.02015799]
 [-0.03743627]]
8 Step:
[[-0.09284195]
 [-0.04999182]]
9 Step:
[[ 0.00492765]
 [-0.00915135]]
10 Step:
[[-0.02269535]
 [-0.01222058]]
11 Step:
[[ 0.00120457]
 [-0.00223706]]
12 Step:
[[-0.00554791]
 [-0.00298734]]
13 Step:
[[ 0.00029446]
 [-0.00054685]]
14 Step:
[[-0.0013562 ]
 [-0.00073026]]
15 Step:
[[ 7.19810461e-05]
 [-1.33679086e-04]]
16 Step:
[[-0.00033152]
 [-0.00017851]]
17 Step:
[[ 1.75958754e-05]
 [-3.26780544e-05]]
18 Step:
[[-8.10415748e-05]
 [-4.36377711e-05]]
19 Step:
[[ 4.30133832e-06]
 [-7.98819974e-06]]
20 Step:
[[-1.98107354e-05]
 [-1.06673190e-05]]
21 Step:
[[ 1.05146865e-06]
 [-1.95272749e-06]]
22 Step:
[[-4.84276417e-06]
 [-2.60764225e-06]]
The optimal value is reported as 10.000000
An opti

# Example 2

Consider the function $f({\bf x})=\displaystyle \frac{1}{2}{\bf x}^tQ{\bf x}+{\bf q}^t {\bf x}+10$
where
$$
{\bf x}=
\left[\begin{array}{cc}
x_{0}\\
x_{1}
\end{array}\right],
Q=
\left[\begin{array}{cc}
20&5\\
5&2
\end{array}\right]
\hbox{ and }
{\bf q}=
\left[\begin{array}{cc}
-14\\
-6
\end{array}\right].
$$
<hr>

In [8]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
xk=[np.array([[40],[-100]])]
#xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
dk=[]
alphak=[]
#dk.append
dk.append(-functionGradient(xk[k],Q,q))
while np.linalg.norm(dk[k])>1e-6 and k<=100:
    print("%d Step:" % k)
    #alphak.append
    alphak.append(determineStepSize(xk[k],Q,q,dk[k]))
    print(dk[k])
    xk.append(xk[k]+alphak[k]*dk[k])
    k=k+1
    dk.append(-functionGradient(xk[k],Q,q))
print("The optimal value is reported as %.6f" % functionValue(xk[-1],Q,q,f0))
print("An optimal solution is given by (%.6f,%.6f)" % (xk[-1][0,0],xk[-1][1,0]))

0 Step:
[[-286]
 [   6]]
1 Step:
[[ 1.62964903]
 [77.67993714]]
2 Step:
[[-188.2105019 ]
 [   3.94847207]]
3 Step:
[[ 1.07243728]
 [51.11951034]]
4 Step:
[[-123.85731827]
 [   2.59840528]]
5 Step:
[[ 0.70574811]
 [33.64065978]]
6 Step:
[[-81.50786027]
 [  1.70995511]]
7 Step:
[[ 0.46443778]
 [22.13820092]]
8 Step:
[[-53.63858493]
 [  1.125285  ]]
9 Step:
[[ 0.3056366 ]
 [14.56867799]]
10 Step:
[[-35.29840906]
 [  0.74052606]]
11 Step:
[[0.20113293]
 [9.58733635]]
12 Step:
[[-23.22913037]
 [  0.48732441]]
13 Step:
[[0.13236129]
 [6.30922163]]
14 Step:
[[-15.2865954 ]
 [  0.32069781]]
15 Step:
[[0.08710414]
 [4.15196423]]
16 Step:
[[-10.05978249]
 [  0.21104439]]
17 Step:
[[0.05732138]
 [2.73231913]]
18 Step:
[[-6.62012836]
 [ 0.13888381]]
19 Step:
[[0.03772198]
 [1.79808096]]
20 Step:
[[-4.35656532]
 [ 0.09139648]]
21 Step:
[[0.02482403]
 [1.18327874]]
22 Step:
[[-2.86696275]
 [ 0.06014607]]
23 Step:
[[0.01633616]
 [0.77869051]]
24 Step:
[[-1.88668705]
 [ 0.03958085]]
25 Step:
[[0.01075

# Example 3

Consider the function $f({\bf x})=\displaystyle \frac{1}{2}{\bf x}^tQ{\bf x}+{\bf q}^t {\bf x}+10$
where
$$
{\bf x}=
\left[\begin{array}{cc}
x_{0}\\
x_{1}
\end{array}\right],
Q=
\left[\begin{array}{cc}
20&5\\
5&16
\end{array}\right]
\hbox{ and }
{\bf q}=
\left[\begin{array}{cc}
-14\\
-6
\end{array}\right].
$$
<hr>

https://ocw.mit.edu/courses/15-084j-nonlinear-programming-spring-2004/9c07ac34609f36bb15967a35a4e77a7b_lec5_steep_desce.pdf

# Theoretic Analysis

Unconstrained Problem:
\begin{align*}
    (\text{P}) \quad \min \quad & f({\bf x})  \\
    \text{s.t. } \quad  & \bar{\bf x} \in X,
\end{align*}
where $\bar{\bf x}=(x_{1},\cdots,x_{n}) \in \mathbb{R}^{n}, f(\bar{\bf x}):\mathbb{R}^{n} \rightarrow \mathbb{R},$ and $X$ is an open set (usually $X = \mathbb{R}^{n}$).
<hr>
Definition:

The direction ${\bf d}$ is called a descent direction of $f({\bf x})$ at ${\bf x} = \bar{\bf x}$ if there is a $\varepsilon>0$ such that for all $\lambda\in(0,\varepsilon)$
$$
f(\bar{\bf x}+\lambda {\bf d}) < f(\bar{\bf x}).
$$
<hr>

A $necessary \, condition$ for local optimality is a statement of the form: "if $\bar{\bf x}$ is a local minimum of (P), then $\bar{\bf x}$ must satisfy$\ldots$". Such a condition helps us identify all candidates for local optima.
<hr>
Theorem:

Suppose that $f({\bf x})$ is differentiable at $\bar{\bf x}$. If there is a vector $d$ such that $\nabla f(\bar{\bf x})^{t}d < 0$,
then there is a $\varepsilon>0$ such that for all $\lambda\in(0,\varepsilon)$, $f(\bar{\bf x}+ \lambda {\bf d}) < f(\bar{\bf x})$, and hence $d$ is a descent direction of $f({\bf x})$ at $\bar{\bf x}$.
<hr>


Theorem:

Suppose that $f({\bf x})$ is twice differentiable at $\bar{\bf x}$. If $\nabla f(\bar{\bf x}) = 0$ and $H(\bar{\bf x})$ is positive definite, then $\bar{\bf x}$ is a (strict) local minimum.
<hr>

<ol>
    <li>In this section, we explore answers to the question of how fast the steepest
        descent algorithm converges.</li>
    <li>We say that an algorithm exhibits linear convergence in the objective function values if there is a constant $\delta < 1$ such that for all $k$ sufficiently large, the iterates $x^{k}$ satisfy: $$\displaystyle \frac{f(x^{k+1})-f(x^{*})}{f(x^{k})-f(x^{*})} \leq \delta,$$ where $x^{*}$ is some optimal value of the problem $P$.</li>
    <li>The above statement says
that the optimality gap shrinks by at least $\delta$ at each iteration.</li>
    <li>Notice that if
$\delta = 0.1$, for example, then the iterates gain an extra digit of accuracy in the
optimal objective function value at each iteration.</li>
    <li>If $\delta = 0.9$, for example,
then the iterates gain an extra digit of accuracy in the optimal objective
function value every 22 iterations, since $(0.9)^{22} \approx 0.10$.</li>
    <li>The quantity $\delta$ above is called the convergence constant. We would like
this constant to be smaller rather than larger.</li>
</ol>
<hr>

https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

<hr>
Suppose that the
eigenvalues of $Q$ are
$$A = a_{1} \geq a_{2} \geq \cdots \geq a_{n} = a > 0,$$
i.e, $A$ and a are the largest and smallest eigenvalues of $Q$.

Then we have
$$\displaystyle \frac{f({\bf x}^{k+1})-f({\bf x}^{*})}{f({\bf x}^{k})-f({\bf x}^{*})} = 1- \displaystyle \frac{1}{\beta}
\leq 1 - \displaystyle \frac{4Aa}{(A+a)^{2}} = \displaystyle \frac{(A-a)^{2}}{(A+a)^{2}}
=: \delta.$$
<hr>

Sensitivity of Steepest Descent Convergence Rate to the Eigenvalue Ratio
$$
\begin{array}{|c|c|c|c|}
    \hline
    A & a & \hbox{Upper Bound on}\delta = \left( \displaystyle \frac{A/a-1}{A/a+1} \right)^{2} &
    \hbox{Number of Iterations to Reduce the Optimality Gap by }10^{-1} \\
    \hline
    1.1 & 1.0 & 0.0023 & 1 \\
    \hline
    3.0 & 1.0 & 0.25 & 2 \\
    \hline
    10.0 & 1.0 & 0.67 & 6 \\
    \hline
    100.0 & 1.0 & 0.96 & 58 \\
    \hline
    200.0 & 1.0 & 0.98 & 116 \\
    \hline
    400.0 & 1.0 & 0.99 & 231 \\
    \hline
\end{array}
$$
<hr>

In [9]:
Q=np.array([[10,4],[4,2]])
q=np.array([[-14],[-6]])
b=np.array([[20]])
eigenvalues, eigenvectors = np.linalg.eig(Q)
a=min(abs(eigenvalues))
A=max(abs(eigenvalues))
print(((A/a-1)/(A/a+1))**2)

0.8888888888888888


In [10]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
b=np.array([[10]])
eigenvalues, eigenvectors = np.linalg.eig(Q)
a=min(abs(eigenvalues))
A=max(abs(eigenvalues))
print(((A/a-1)/(A/a+1))**2)

0.8760330578512396


In [11]:
Q=np.array([[20,5],[5,16]])
q=np.array([[-14],[-6]])
b=np.array([[10]])
eigenvalues, eigenvectors = np.linalg.eig(Q)
a=min(abs(eigenvalues))
A=max(abs(eigenvalues))
print(((A/a-1)/(A/a+1))**2)

0.08950617283950614


In [12]:
Q=np.array([[20,5],[5,16]])
q=np.array([[-14],[-6]])
b=np.array([[10]])
eigenvalues, eigenvectors = np.linalg.eig(Q)
a=min(abs(eigenvalues))
A=max(abs(eigenvalues))
print(((A/a-1)/(A/a+1))**2)

0.08950617283950614


In [13]:
No,xk0,xk1=[0,1,2,3,4,5],[11,12,13,14,15,16],[21,22,23,24,25,26]
Table = {"k": No,"$x_{0}^{k}$":xk0,"$x_{1}^{k}$":xk1,"$d_{0}^{k}$":xk1,"$d_{1}^{k}$":xk1,"norm":xk1,"Step Size":xk1,"函數值":xk1}
pd.DataFrame(Table).sort_values(by = "k")

k  $x_{0}^{k}$  $x_{1}^{k}$  $d_{0}^{k}$  $d_{1}^{k}$  norm  Step Size  函數值
0  0           11           21           21           21    21         21   21
1  1           12           22           22           22    22         22   22
2  2           13           23           23           23    23         23   23
3  3           14           24           24           24    24         24   24
4  4           15           25           25           25    25         25   25
5  5           16           26           26           26    26         26   26

In [14]:
No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#,empty ist
for i in range(len(alphak)):
    No.append(i)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
    #type(alphak[i]) 類別是矩陣
    #type(alphak[i][0])類別是 float
Table = {"k": No,"$x_{0}^{k}$":xk0,"$x_{1}^{k}$":xk1,"$d_{0}^{k}$":dk0,"$d_{1}^{k}$":dk1,"norm":norm_d0,"Step Size":alphak0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

k  $x_{0}^{k}$  $x_{1}^{k}$   $d_{0}^{k}$   $d_{1}^{k}$        norm  \
0    0    40.000000  -100.000000 -2.860000e+02  6.000000e+00  286.062930   
1    1    25.542693   -99.696700  1.629649e+00  7.767994e+01   77.697029   
2    2    26.277558   -64.668130 -1.882105e+02  3.948472e+00  188.251915   
3    3    16.763512   -64.468535  1.072437e+00  5.111951e+01   51.130758   
4    4    17.247111   -41.416980 -1.238573e+02  2.598405e+00  123.884571   
..  ..          ...          ...           ...           ...         ...   
84  84    -0.133332     3.333331 -6.668597e-06  1.399006e-07    0.000007   
85  85    -0.133333     3.333331  3.799815e-08  1.811245e-06    0.000002   
86  86    -0.133333     3.333332 -4.388461e-06  9.206562e-08    0.000004   
87  87    -0.133333     3.333332  2.500577e-08  1.191942e-06    0.000001   
88  88    -0.133333     3.333332 -2.887953e-06  6.058641e-08    0.000003   

    Step Size           函數值  
0    0.050550  76050.000000  
1    0.450935  73557.718845  
2    0.050550  31894.357109  
3    0.450935  30818.215834  
4    0.050550  13142.984170  
..        ...           ...  
84   0.050550     78.710999  
85   0.450935     78.710999  
86   0.050550     78.711037  
87   0.450935     78.711037  
88   0.050550     78.711062  

[89 rows x 8 columns]

In [20]:
Q=np.array([[20,5],[5,2]])
q=np.array([[-14],[-6]])
f0=np.array([[10]])
No,xk0,xk1,dk0,dk1,norm_d0,alphak0,obj0=[],[],[],[],[],[],[],[]#,empty ist
for i in range(10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
for i in range(19,len(alphak),10):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
for i in range(len(alphak)-1,len(alphak)):
    No.append(i+1)
    xk0.append(xk[i][0,0])
    xk1.append(xk[i][1,0])
    dk0.append(dk[i][0,0])
    dk1.append(dk[i][1,0])
    norm_d0.append(np.linalg.norm(dk[i]))
    alphak0.append(alphak[i][0])
    obj0.append(functionValue(xk[i],Q,q,f0)[0,0])
    #type(alphak[i]) 類別是矩陣
    #type(alphak[i][0])類別是 float
Table = {"k": No,"$x_{1}^{k}$":xk0,"$x_{2}^{k}$":xk1,"norm":norm_d0,"Step Size":alphak0,"函數值":obj0}
#pd.DataFrame(Table).sort_values(by = "k")
pd.DataFrame(Table)

k  $x_{1}^{k}$  $x_{2}^{k}$        norm  Step Size          函數值
0    1    40.000000  -100.000000  286.062930   0.050550  6050.000000
1    2    25.542693   -99.696700   77.697029   0.450935  3981.695128
2    3    26.277558   -64.668130  188.251915   0.050550  2620.587793
3    4    16.763512   -64.468535   51.130758   0.450935  1724.872077
4    5    17.247111   -41.416980  123.884571   0.050550  1135.420663
5    6    10.986120   -41.285630   33.648062   0.450935   747.515255
6    7    11.304366   -26.115894   81.525795   0.050550   492.242977
7    8     7.184142   -26.029455   22.143072   0.450935   324.253734
8    9     7.393573   -16.046575   53.650387   0.050550   213.703595
9   10     4.682141   -15.989692   14.571884   0.450935   140.952906
10  20     0.460997     0.948466    1.798477   0.450935     3.066216
11  30    -0.059980     3.038991    0.221970   0.450935     0.965823
12  40    -0.124280     3.297005    0.027396   0.450935     0.933828
13  50    -0.132216     3.328850    0.003381   0.450935     0.933341
14  60    -0.133195     3.332780    0.000417   0.450935     0.933333
15  70    -0.133316     3.333265    0.000052   0.450935     0.933333
16  80    -0.133331     3.333325    0.000006   0.450935     0.933333
17  89    -0.133333     3.333332    0.000003   0.050550     0.933333

In [17]:
P=np.zeros((2,2))
P[0,0]=1/np.sqrt(2)
P[0,1]=-1/np.sqrt(2)
P[1,0]=1/np.sqrt(2)
P[1,1]=1/np.sqrt(2)